/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.sql.SQLException;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import com.com2008.journalmanagementsystem.model.*;
import com.com2008.journalmanagementsystem.util.database.Database;

/**
 *
 * @author Xuan
 */
public class AuthorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReaderPanel
     */
    private String email;
    public AuthorPanel(String email) {
        initComponents();

        this.email = email;

        updateSubmissions();
    }

    private void updateSubmissions(){
        submissionTree.removeAll();
        articalOutterPanel.removeAll();

        DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("Submissions");

        DefaultMutableTreeNode submittedNode = new DefaultMutableTreeNode("Submitted");
        DefaultMutableTreeNode reviewedNode = new DefaultMutableTreeNode("Reviewed");
        DefaultMutableTreeNode responsedNode = new DefaultMutableTreeNode("Responsed");

        rootNode.add(submittedNode);
        rootNode.add(reviewedNode);
        rootNode.add(responsedNode);

        try {
            List<SubmissionAuthor> submissionAuthors = Database.read("SubmissionAuthor", new SubmissionAuthor(null, null, email));
            for (SubmissionAuthor submissionAuthor : submissionAuthors) {
                Submission submission = Database.read("Submission", new Submission(submissionAuthor.getIssn(), submissionAuthor.getSubmissionID(), null, null, null, null, null, null, null)).get(0);
                DefaultMutableTreeNode submissionNode = new DefaultMutableTreeNode(submission);
                switch(submission.getStatus()){
                    case SUBMITTED:
                        submittedNode.add(submissionNode);
                        break;
                    case REVIEWED:
                        reviewedNode.add(submissionNode);
                        break;
                    case RESPONSED:
                        responsedNode.add(submissionNode);
                        break;
                }
            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        submissionTree.setModel(new DefaultTreeModel(rootNode));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        submissionScrollPane = new javax.swing.JScrollPane();
        submissionTree = new javax.swing.JTree();
        articalOutterPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        submissionTree.setToolTipText("");
        submissionTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                submissionTreeValueChanged(evt);
            }
        });
        submissionScrollPane.setViewportView(submissionTree);

        jSplitPane1.setLeftComponent(submissionScrollPane);

        articalOutterPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(articalOutterPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void submissionTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_submissionTreeValueChanged
        DefaultMutableTreeNode lastNode = (DefaultMutableTreeNode)evt.getPath().getLastPathComponent();
        Object userObject = lastNode.getUserObject();
        if(userObject.getClass() == Submission.class){
            Submission submission = (Submission)userObject;
            articalOutterPanel.removeAll();
            ArticlePanel articlePanel = new ArticlePanel(submission, UserRole.AUTHOR, email);
            articlePanel.getSubmitAllResponsesBtn().addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    updateSubmissions();
                }
            });
            articalOutterPanel.add(articlePanel, java.awt.BorderLayout.CENTER);
            articalOutterPanel.revalidate();
        }
    }//GEN-LAST:event_submissionTreeValueChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel articalOutterPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JScrollPane submissionScrollPane;
    private javax.swing.JTree submissionTree;
    // End of variables declaration//GEN-END:variables
}
