/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.sql.SQLException;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;

import com.com2008.journalmanagementsystem.model.*;
import com.com2008.journalmanagementsystem.util.database.Database;

/**
 *
 * @author Xuan
 */
public class AuthorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReaderPanel
     */
    private String email;
    public AuthorPanel(String email) {
        initComponents();

        this.email = email;

        sumbissionList.removeAll();
        articalOutterPanel.removeAll();


        DefaultListModel listModel = new DefaultListModel<>();

        try {
            List<SubmissionAuthor> submissionAuthors = Database.read("SubmissionAuthor", new SubmissionAuthor(null, null, email));
            for (SubmissionAuthor submissionAuthor : submissionAuthors) {
                Submission submission = Database.read("Submission", new Submission(submissionAuthor.getIssn(), submissionAuthor.getSubmissionID(), null, null, null, null, null, null, null)).get(0);
                listModel.addElement(submission);
            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        sumbissionList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sumbissionScrollPane1 = new javax.swing.JScrollPane();
        sumbissionList = new javax.swing.JList<>();
        articalOutterPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        sumbissionList.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        sumbissionList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sumbissionList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sumbissionListValueChanged(evt);
            }
        });
        sumbissionScrollPane1.setViewportView(sumbissionList);

        jSplitPane1.setLeftComponent(sumbissionScrollPane1);

        articalOutterPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(articalOutterPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void sumbissionListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_sumbissionListValueChanged

        Submission submission = ((javax.swing.JList<Submission>)evt.getSource()).getSelectedValue();
        articalOutterPanel.removeAll();
        articalOutterPanel.add(new ArticlePanel(submission, UserRole.AUTHOR, email), java.awt.BorderLayout.CENTER);
        articalOutterPanel.revalidate();
    }//GEN-LAST:event_sumbissionListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel articalOutterPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<Submission> sumbissionList;
    private javax.swing.JScrollPane sumbissionScrollPane1;
    // End of variables declaration//GEN-END:variables
}
