/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.awt.Dimension;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import com.com2008.journalmanagementsystem.model.Edition;
import com.com2008.journalmanagementsystem.model.EditorOnBoard;
import com.com2008.journalmanagementsystem.model.Journal;
import com.com2008.journalmanagementsystem.util.database.Database;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Jordan Marsh
 */
public class CreateJournalPanel extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form ProfilePanel
     */
    public CreateJournalPanel() {
        initComponents();
    }
    
    private String email;

    public CreateJournalPanel(String email) {
        initComponents();
        
        this.email = email;
    }
    
    public boolean verify(String is,String jo){
        String issn = is;
        String journalName = jo;

        if(issn.isEmpty() || journalName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please complete all the fields.", "Register", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        String patternString = "^ISSN [0-9]{4}-[0-9]{3}[0-9X]$";
        Pattern pattern = Pattern.compile(patternString);
        Matcher matcher = pattern.matcher(issn);
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(null, "Invalid ISSN.", "Register", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        innerPanel = new javax.swing.JPanel();
        createJournalPanel = new javax.swing.JPanel();
        createJournalLabel = new javax.swing.JLabel();
        createJournalMainPanel = new javax.swing.JPanel();
        createJournalInnerPanel = new javax.swing.JPanel();
        newIssnPanel = new javax.swing.JPanel();
        newIssnLabelPanel = new javax.swing.JPanel();
        newIssnLabel = new javax.swing.JLabel();
        filler38 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        filler39 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        newIssnField = new javax.swing.JTextField();
        newJournalNamePanel = new javax.swing.JPanel();
        newJournalNameLabelPanel = new javax.swing.JPanel();
        newJournalNameLabel = new javax.swing.JLabel();
        filler51 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        filler52 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        newJournalNameField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        filler59 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler60 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler61 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler62 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        jSeparator1 = new javax.swing.JSeparator();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));

        setLayout(new java.awt.BorderLayout());

        mainPanel.setLayout(new java.awt.BorderLayout());

        innerPanel.setLayout(new javax.swing.BoxLayout(innerPanel, javax.swing.BoxLayout.PAGE_AXIS));

        createJournalPanel.setLayout(new java.awt.BorderLayout());

        createJournalLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        createJournalLabel.setText("Create Journal");
        createJournalPanel.add(createJournalLabel, java.awt.BorderLayout.NORTH);

        createJournalMainPanel.setLayout(new java.awt.BorderLayout());

        createJournalInnerPanel.setLayout(new javax.swing.BoxLayout(createJournalInnerPanel, javax.swing.BoxLayout.PAGE_AXIS));

        newIssnPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        newIssnPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        newIssnPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        newIssnPanel.setLayout(new java.awt.BorderLayout());

        newIssnLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        newIssnLabelPanel.setPreferredSize(getTextfieldLabelSize());
        newIssnLabelPanel.setLayout(new java.awt.BorderLayout());

        newIssnLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        newIssnLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        newIssnLabel.setText("New ISSN");
        newIssnLabelPanel.add(newIssnLabel, java.awt.BorderLayout.CENTER);
        newIssnLabelPanel.add(filler38, java.awt.BorderLayout.EAST);

        newIssnPanel.add(newIssnLabelPanel, java.awt.BorderLayout.WEST);
        newIssnPanel.add(filler39, java.awt.BorderLayout.SOUTH);
        newIssnPanel.add(newIssnField, java.awt.BorderLayout.CENTER);

        createJournalInnerPanel.add(newIssnPanel);

        newJournalNamePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        newJournalNamePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        newJournalNamePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        newJournalNamePanel.setLayout(new java.awt.BorderLayout());

        newJournalNameLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        newJournalNameLabelPanel.setPreferredSize(getTextfieldLabelSize());
        newJournalNameLabelPanel.setLayout(new java.awt.BorderLayout());

        newJournalNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        newJournalNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        newJournalNameLabel.setText("New Journal Name");
        newJournalNameLabelPanel.add(newJournalNameLabel, java.awt.BorderLayout.CENTER);
        newJournalNameLabelPanel.add(filler51, java.awt.BorderLayout.EAST);

        newJournalNamePanel.add(newJournalNameLabelPanel, java.awt.BorderLayout.WEST);
        newJournalNamePanel.add(filler52, java.awt.BorderLayout.SOUTH);
        newJournalNamePanel.add(newJournalNameField, java.awt.BorderLayout.CENTER);

        createJournalInnerPanel.add(newJournalNamePanel);

        confirmButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        createJournalInnerPanel.add(confirmButton);

        createJournalMainPanel.add(createJournalInnerPanel, java.awt.BorderLayout.CENTER);
        createJournalMainPanel.add(filler59, java.awt.BorderLayout.NORTH);
        createJournalMainPanel.add(filler60, java.awt.BorderLayout.SOUTH);
        createJournalMainPanel.add(filler61, java.awt.BorderLayout.WEST);
        createJournalMainPanel.add(filler62, java.awt.BorderLayout.EAST);

        createJournalPanel.add(createJournalMainPanel, java.awt.BorderLayout.CENTER);

        innerPanel.add(createJournalPanel);
        innerPanel.add(filler1);
        innerPanel.add(jSeparator1);

        mainPanel.add(innerPanel, java.awt.BorderLayout.CENTER);
        mainPanel.add(filler3, java.awt.BorderLayout.WEST);
        mainPanel.add(filler4, java.awt.BorderLayout.EAST);
        mainPanel.add(filler5, java.awt.BorderLayout.NORTH);
        mainPanel.add(filler6, java.awt.BorderLayout.SOUTH);

        mainScrollPane.setViewportView(mainPanel);

        add(mainScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String newIssn = newIssnField.getText();
        String newJournalName = newJournalNameField.getText();
        if (verify(newIssn, newJournalName)){
            try {
                List<Journal> journals = Database.read("Journal", new Journal(newIssn,null,null));
                if (journals.size() > 0){
                    JOptionPane.showMessageDialog(null, "Journal already exists", "Register", JOptionPane.ERROR_MESSAGE);
                }
                else {
                    Database.write("Journal", new Journal(newIssn, newJournalName, email));
                    Database.write("EditorOnBoard", new EditorOnBoard(newIssn, email));
                    Database.write("Edition", new Edition(newIssn,1,1));
                    JOptionPane.showMessageDialog(null, "Success", "Register", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CreateJournalPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }                                             

    // <editor-fold defaultstate="collapsed" desc="Element size">
    private Dimension textfieldLabelSize = new Dimension(120, 100);
    private Dimension getTextfieldLabelSize(){
        return textfieldLabelSize;
    }
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel createJournalInnerPanel;
    private javax.swing.JLabel createJournalLabel;
    private javax.swing.JPanel createJournalMainPanel;
    private javax.swing.JPanel createJournalPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler38;
    private javax.swing.Box.Filler filler39;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler51;
    private javax.swing.Box.Filler filler52;
    private javax.swing.Box.Filler filler59;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler60;
    private javax.swing.Box.Filler filler61;
    private javax.swing.Box.Filler filler62;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JTextField newIssnField;
    private javax.swing.JLabel newIssnLabel;
    private javax.swing.JPanel newIssnLabelPanel;
    private javax.swing.JPanel newIssnPanel;
    private javax.swing.JTextField newJournalNameField;
    private javax.swing.JLabel newJournalNameLabel;
    private javax.swing.JPanel newJournalNameLabelPanel;
    private javax.swing.JPanel newJournalNamePanel;
    // End of variables declaration//GEN-END:variables
}
