/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import com.com2008.journalmanagementsystem.model.EditorOnBoard;
import com.com2008.journalmanagementsystem.model.Journal;
import com.com2008.journalmanagementsystem.model.Submission;
import com.com2008.journalmanagementsystem.util.database.Database;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import static javax.swing.BoxLayout.Y_AXIS;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Jorda
 */
public class DecisionPanel extends javax.swing.JPanel {

    /**
     * Creates new form DecisionPanel
     */
    public DecisionPanel() {
        initComponents();
    }
    
    public DecisionPanel(String email) {
        initComponents();
        List<Journal> journals = new ArrayList<>();
        List<List<Submission>> submissions = new ArrayList<>();
        try {
            List<EditorOnBoard> editorsOnBoard = Database.read("EditorOnBoard", new EditorOnBoard(null,email));
            for (EditorOnBoard editorOnBoard:editorsOnBoard){
                Journal currentJournal = Database.read("Journal", new Journal(editorOnBoard.getIssn(),null,null,null,null)).get(0);
                journals.add(currentJournal);
                List<Submission> currentSubmissions = Database.read("Submission", new Submission(editorOnBoard.getIssn(),null,null,null,null,null,null,null,null));
                submissions.add(currentSubmissions);
                
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
        
    journalPanel.setLayout(new BoxLayout(journalPanel,Y_AXIS));
    ArrayList<JButton> buttonList = new ArrayList<>();
    for (int i=0; i<journals.size(); i++){
        for (Submission sub: submissions.get(i)){
            JLabel label = new JLabel("Journal: "+journals.get(i).getJournalName()+" "
                    + "Title: "+sub.getTitle());
            label.setFont(new Font("Tahoma",Font.PLAIN,14));
            buttonList.add(new JButton("See this submission"));
            //add button listener with information from the current journal
            buttonList.get(buttonList.size()-1).addActionListener(new LinkSubmissionActionListener(sub,email));
            journalPanel.add(label);
            journalPanel.add(buttonList.get(buttonList.size()-1));
            journalPanel.add(Box.createRigidArea(new Dimension(20, 20)));
        }
            
        }
        journalPanel.revalidate();
        journalPanel.repaint();
    }
    private class LinkSubmissionActionListener implements ActionListener {
    	
    	Submission su;
    	String em;
    	
        public LinkSubmissionActionListener(Submission sub, String email) {
        	this.su = sub;
        	this.em = email;
        	
	}

        public void actionPerformed(ActionEvent e) {
            JFrame submissionFrame = new JFrame();
            submissionFrame.add(new ArticlePanel(su,UserRole.EDITOR,em));
            submissionFrame.setBounds(0, 0, 250, 250);
            submissionFrame.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        journalPanel = new javax.swing.JPanel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Journal List");

        javax.swing.GroupLayout journalPanelLayout = new javax.swing.GroupLayout(journalPanel);
        journalPanel.setLayout(journalPanelLayout);
        journalPanelLayout.setHorizontalGroup(
            journalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        journalPanelLayout.setVerticalGroup(
            journalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(journalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(journalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel journalPanel;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
