/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;

/**
 *
 * @author Xuan
 */
public class LoadingPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoadingPanel
     */
    public LoadingPanel() {
        initComponents();
    }

    private static Timer timer;
	private int step;
	private int x = 0;

    public LoadingPanel(int frameRate, int speed, int size) {
		initComponents();
		this.setMinimumSize(new Dimension(size, size));
		this.setMaximumSize(new Dimension(size, size));
		this.setPreferredSize(new Dimension(size, size));
		this.step = speed / frameRate;
		timer = new Timer(1000 / frameRate, new ReboundListener());
		timer.start();
    }
    
    private class ReboundListener implements ActionListener {
		@Override
		public void actionPerformed(ActionEvent e) {
			if (x < 360)
				x = x - step;
			else
				x = 0;
			repaint();
		}
	}

	public void paintComponent(Graphics page) {
		super.paintComponent(page);
		drawArc(page);
	}

	private void drawArc(Graphics g) {
		Graphics2D g2d = (Graphics2D) g.create();
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
		int width = getWidth();
		int height = getHeight();
		int or = 30;
		int ir = 25;
		g2d.setColor(new java.awt.Color(204, 204, 204));
		g2d.fillArc(width / 2 - or, height / 2 - or, or*2, or*2, x, 120);
		g2d.setColor(Theme.getBgColor());
		g2d.fillArc(width / 2 - ir, height / 2 - ir, ir*2, ir*2, 0, 360);
		g2d.dispose();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(Theme.getBgColor());
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
