/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Xuan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        titleLabel = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        closeBtn = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        startupPanel = new javax.swing.JPanel();
        selePanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        welLabel = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginSelPanel = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        loginReaderBtn = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginReaderLabelTop = new javax.swing.JLabel();
        loginReaderLabelBot = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        loginUserBtn = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        registerPanel = new javax.swing.JPanel();
        registerAuthorBtn = new javax.swing.JPanel();
        registerAuthorLabel = new javax.swing.JLabel();
        registerJournalBtn = new javax.swing.JPanel();
        registerJournalLabel = new javax.swing.JLabel();
        regAuthorPanel = new javax.swing.JPanel();
        regAuthorToobarPanel = new javax.swing.JPanel();
        regAuthorBackBtn = new javax.swing.JPanel();
        regAuthorBackLabel = new javax.swing.JLabel();
        registerAuthorPanel = new com.com2008.journalmanagementsystem.frame.RegisterPanel();
        regAuthorBtnPanel = new javax.swing.JPanel();
        regAuthorBtn = new javax.swing.JPanel();
        regAuthorLabel = new javax.swing.JLabel();
        filler66 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        regJournalPanel = new javax.swing.JPanel();
        regJournalToobarPanel = new javax.swing.JPanel();
        regJournalbackBtn = new javax.swing.JPanel();
        regJournalbackLabel = new javax.swing.JLabel();
        regJournalMainScrollPane = new javax.swing.JScrollPane();
        regJournalMainPanel = new javax.swing.JPanel();
        regJournalInnerPanel = new javax.swing.JPanel();
        regJournalJournalNamePanel = new javax.swing.JPanel();
        regJournalJournalNameLabelPanel = new javax.swing.JPanel();
        regJournalJournalNameLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalJournalNameTextField = new javax.swing.JTextField();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regJournalISSNPanel = new javax.swing.JPanel();
        regJournalISSNLabelPanel = new javax.swing.JPanel();
        regJournalISSNLabel = new javax.swing.JLabel();
        filler31 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalISSNTextField = new javax.swing.JTextField();
        filler32 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regJournalEmailPanel = new javax.swing.JPanel();
        regJournalEmailLabelPanel = new javax.swing.JPanel();
        regJournalEmailLabel = new javax.swing.JLabel();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalEmailTextField = new javax.swing.JTextField();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regJournalPasswordPanel = new javax.swing.JPanel();
        regJournalPasswordLabelPanel = new javax.swing.JPanel();
        regJournalPasswordLabel = new javax.swing.JLabel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalPasswordField = new javax.swing.JPasswordField();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regJournalRePasswordPanel = new javax.swing.JPanel();
        regJournalRePasswordLabelPanel = new javax.swing.JPanel();
        regJournalRePasswordLabel = new javax.swing.JLabel();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalRePasswordField = new javax.swing.JPasswordField();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regJournalUniversityPanel = new javax.swing.JPanel();
        regJournalUniversityLabelPanel = new javax.swing.JPanel();
        regJournalUniversityLabel = new javax.swing.JLabel();
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalUniversityTextField = new javax.swing.JTextField();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regJournalTitlePanel = new javax.swing.JPanel();
        regJournalTitleLabelPanel = new javax.swing.JPanel();
        regJournalTitleLabel = new javax.swing.JLabel();
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalTitleComboBox = new javax.swing.JComboBox<>();
        filler30 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regJournalForenamePanel = new javax.swing.JPanel();
        regJournalForenameLabelPanel = new javax.swing.JPanel();
        regJournalForenameLabel = new javax.swing.JLabel();
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalForenameTextField = new javax.swing.JTextField();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regJournalSurnamePanel = new javax.swing.JPanel();
        regJournalSurnameLabelPanel = new javax.swing.JPanel();
        regJournalSurnameLabel = new javax.swing.JLabel();
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalSurnameTextField = new javax.swing.JTextField();
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        regJournalBtnPanel = new javax.swing.JPanel();
        regJournalBtn = new javax.swing.JPanel();
        regJournalLabel = new javax.swing.JLabel();
        filler45 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        loginPanel = new javax.swing.JPanel();
        loginToobarPanel = new javax.swing.JPanel();
        loginbackBtn = new javax.swing.JPanel();
        regJournalbackLabel1 = new javax.swing.JLabel();
        loginMainPanel = new javax.swing.JPanel();
        loginInnerPanel = new javax.swing.JPanel();
        loginRolePanel = new javax.swing.JPanel();
        loginRoleLabelPanel = new javax.swing.JPanel();
        loginRoleLabel = new javax.swing.JLabel();
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        loginRoleComboBox = new javax.swing.JComboBox<>();
        filler37 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        loginEmailPanel = new javax.swing.JPanel();
        loginEmailLabelPanel = new javax.swing.JPanel();
        loginEmailLabel = new javax.swing.JLabel();
        filler38 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        loginEmailTextField = new javax.swing.JTextField();
        filler39 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        loginPasswordPanel = new javax.swing.JPanel();
        loginPasswordLabelPanel = new javax.swing.JPanel();
        loginPasswordLabel = new javax.swing.JLabel();
        filler51 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        loginPasswordField = new javax.swing.JPasswordField();
        filler52 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler59 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler60 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler61 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler62 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        loginBtnPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        filler63 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(getStartupLocation());
        setUndecorated(true);
        setPreferredSize(getFrameSize());
        setSize(getFrameSize());

        bg.setBackground(Theme.getBgColor());
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(Theme.getBgColor());
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        headerPanel.setLayout(new javax.swing.BoxLayout(headerPanel, javax.swing.BoxLayout.LINE_AXIS));
        headerPanel.add(filler10);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 204, 204));
        titleLabel.setText("Login");
        headerPanel.add(titleLabel);
        headerPanel.add(filler12);

        closeBtn.setBackground(Theme.getFgColor());
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.setMaximumSize(new java.awt.Dimension(30, 30));
        closeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        closeBtn.setLayout(new java.awt.BorderLayout());

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("×");
        closeBtn.add(closeLabel, java.awt.BorderLayout.CENTER);

        headerPanel.add(closeBtn);

        bg.add(headerPanel, java.awt.BorderLayout.NORTH);

        mainPanel.setBackground(Theme.getBgColor());
        mainPanel.setLayout(new java.awt.CardLayout());

        startupPanel.setBackground(Theme.getBgColor());
        startupPanel.setLayout(new java.awt.BorderLayout());

        selePanel.setBackground(Theme.getBgColor());
        selePanel.setLayout(new javax.swing.BoxLayout(selePanel, javax.swing.BoxLayout.PAGE_AXIS));
        selePanel.add(filler4);

        welLabel.setBackground(new java.awt.Color(255, 255, 255));
        welLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welLabel.setForeground(new java.awt.Color(204, 204, 204));
        welLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welLabel.setText("Welcome");
        welLabel.setAlignmentX(0.5F);
        selePanel.add(welLabel);
        selePanel.add(filler5);

        loginSelPanel.setBackground(Theme.getBgColor());
        loginSelPanel.setLayout(new javax.swing.BoxLayout(loginSelPanel, javax.swing.BoxLayout.LINE_AXIS));
        loginSelPanel.add(filler8);

        loginReaderBtn.setBackground(Theme.getFgColor());
        loginReaderBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginReaderBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        loginReaderBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        loginReaderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginReaderBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginReaderBtn.setLayout(new java.awt.GridLayout(4, 1));
        loginReaderBtn.add(filler11);

        loginReaderLabelTop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginReaderLabelTop.setForeground(new java.awt.Color(204, 204, 204));
        loginReaderLabelTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginReaderLabelTop.setText("Enter as a");
        loginReaderBtn.add(loginReaderLabelTop);

        loginReaderLabelBot.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginReaderLabelBot.setForeground(new java.awt.Color(204, 204, 204));
        loginReaderLabelBot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginReaderLabelBot.setText("Reader");
        loginReaderBtn.add(loginReaderLabelBot);

        loginSelPanel.add(loginReaderBtn);
        loginSelPanel.add(filler7);

        loginUserBtn.setBackground(Theme.getFgColor());
        loginUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginUserBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        loginUserBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        loginUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginUserBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginUserBtn.setLayout(new java.awt.BorderLayout());

        loginUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        loginUserLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginUserLabel.setText("Login");
        loginUserBtn.add(loginUserLabel, java.awt.BorderLayout.CENTER);

        loginSelPanel.add(loginUserBtn);
        loginSelPanel.add(filler9);

        selePanel.add(loginSelPanel);
        selePanel.add(filler6);

        startupPanel.add(selePanel, java.awt.BorderLayout.CENTER);

        registerPanel.setBackground(Theme.getBgColor());
        registerPanel.setLayout(new java.awt.GridLayout(1, 2));

        registerAuthorBtn.setBackground(Theme.getFgColor());
        registerAuthorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerAuthorBtn.setMaximumSize(new java.awt.Dimension(100, 30));
        registerAuthorBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        registerAuthorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerAuthorBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        registerAuthorBtn.setLayout(new java.awt.BorderLayout());

        registerAuthorLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerAuthorLabel.setForeground(new java.awt.Color(204, 204, 204));
        registerAuthorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerAuthorLabel.setText("I want to be a author");
        registerAuthorBtn.add(registerAuthorLabel, java.awt.BorderLayout.CENTER);

        registerPanel.add(registerAuthorBtn);

        registerJournalBtn.setBackground(Theme.getFgColor());
        registerJournalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerJournalBtn.setMaximumSize(new java.awt.Dimension(100, 30));
        registerJournalBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        registerJournalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerJournalBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        registerJournalBtn.setLayout(new java.awt.BorderLayout());

        registerJournalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerJournalLabel.setForeground(new java.awt.Color(204, 204, 204));
        registerJournalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerJournalLabel.setText("I want to register a journal");
        registerJournalBtn.add(registerJournalLabel, java.awt.BorderLayout.CENTER);

        registerPanel.add(registerJournalBtn);

        startupPanel.add(registerPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(startupPanel, "startupPanel");

        regAuthorPanel.setBackground(Theme.getBgColor());
        regAuthorPanel.setLayout(new java.awt.BorderLayout());

        regAuthorToobarPanel.setBackground(Theme.getBgColor());
        regAuthorToobarPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        regAuthorToobarPanel.setLayout(new javax.swing.BoxLayout(regAuthorToobarPanel, javax.swing.BoxLayout.LINE_AXIS));

        regAuthorBackBtn.setBackground(Theme.getFgColor());
        regAuthorBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regAuthorBackBtn.setMaximumSize(new java.awt.Dimension(60, 30));
        regAuthorBackBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        regAuthorBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        regAuthorBackBtn.setLayout(new java.awt.BorderLayout());

        regAuthorBackLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regAuthorBackLabel.setForeground(new java.awt.Color(255, 255, 255));
        regAuthorBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regAuthorBackLabel.setText("< Back");
        regAuthorBackBtn.add(regAuthorBackLabel, java.awt.BorderLayout.CENTER);

        regAuthorToobarPanel.add(regAuthorBackBtn);

        regAuthorPanel.add(regAuthorToobarPanel, java.awt.BorderLayout.NORTH);
        regAuthorPanel.add(registerAuthorPanel, java.awt.BorderLayout.CENTER);

        regAuthorBtnPanel.setBackground(Theme.getBgColor());
        regAuthorBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regAuthorBtnPanel.setMaximumSize(new java.awt.Dimension(100, 60));
        regAuthorBtnPanel.setLayout(new java.awt.BorderLayout());

        regAuthorBtn.setBackground(Theme.getFgColor());
        regAuthorBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regAuthorBtn.setMaximumSize(new java.awt.Dimension(100, 40));
        regAuthorBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        regAuthorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regAuthorBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        regAuthorBtn.setLayout(new java.awt.BorderLayout());

        regAuthorLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regAuthorLabel.setForeground(new java.awt.Color(204, 204, 204));
        regAuthorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regAuthorLabel.setText("Register");
        regAuthorBtn.add(regAuthorLabel, java.awt.BorderLayout.CENTER);

        regAuthorBtnPanel.add(regAuthorBtn, java.awt.BorderLayout.CENTER);
        regAuthorBtnPanel.add(filler66, java.awt.BorderLayout.SOUTH);

        regAuthorPanel.add(regAuthorBtnPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(regAuthorPanel, "regAuthorPanel");

        regJournalPanel.setBackground(Theme.getBgColor());
        regJournalPanel.setLayout(new java.awt.BorderLayout());

        regJournalToobarPanel.setBackground(Theme.getBgColor());
        regJournalToobarPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        regJournalToobarPanel.setLayout(new javax.swing.BoxLayout(regJournalToobarPanel, javax.swing.BoxLayout.LINE_AXIS));

        regJournalbackBtn.setBackground(Theme.getFgColor());
        regJournalbackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regJournalbackBtn.setMaximumSize(new java.awt.Dimension(60, 30));
        regJournalbackBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        regJournalbackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        regJournalbackBtn.setLayout(new java.awt.BorderLayout());

        regJournalbackLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regJournalbackLabel.setForeground(new java.awt.Color(255, 255, 255));
        regJournalbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regJournalbackLabel.setText("< Back");
        regJournalbackBtn.add(regJournalbackLabel, java.awt.BorderLayout.CENTER);

        regJournalToobarPanel.add(regJournalbackBtn);

        regJournalPanel.add(regJournalToobarPanel, java.awt.BorderLayout.NORTH);

        regJournalMainScrollPane.setBackground(Theme.getBgColor());
        regJournalMainScrollPane.setBorder(null);

        regJournalMainPanel.setBackground(Theme.getBgColor());
        regJournalMainPanel.setLayout(new java.awt.BorderLayout());

        regJournalInnerPanel.setBackground(Theme.getBgColor());
        regJournalInnerPanel.setLayout(new javax.swing.BoxLayout(regJournalInnerPanel, javax.swing.BoxLayout.PAGE_AXIS));

        regJournalJournalNamePanel.setBackground(Theme.getBgColor());
        regJournalJournalNamePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalJournalNamePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalJournalNamePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalJournalNamePanel.setLayout(new java.awt.BorderLayout());

        regJournalJournalNameLabelPanel.setBackground(Theme.getBgColor());
        regJournalJournalNameLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalJournalNameLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalJournalNameLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalJournalNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalJournalNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalJournalNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalJournalNameLabel.setText("Journal name:");
        regJournalJournalNameLabelPanel.add(regJournalJournalNameLabel, java.awt.BorderLayout.CENTER);
        regJournalJournalNameLabelPanel.add(filler1, java.awt.BorderLayout.EAST);

        regJournalJournalNamePanel.add(regJournalJournalNameLabelPanel, java.awt.BorderLayout.WEST);

        regJournalJournalNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalJournalNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regJournalJournalNamePanel.add(regJournalJournalNameTextField, java.awt.BorderLayout.CENTER);
        regJournalJournalNamePanel.add(filler15, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalJournalNamePanel);

        regJournalISSNPanel.setBackground(Theme.getBgColor());
        regJournalISSNPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalISSNPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalISSNPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalISSNPanel.setLayout(new java.awt.BorderLayout());

        regJournalISSNLabelPanel.setBackground(Theme.getBgColor());
        regJournalISSNLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalISSNLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalISSNLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalISSNLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalISSNLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalISSNLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalISSNLabel.setText("ISSN:");
        regJournalISSNLabelPanel.add(regJournalISSNLabel, java.awt.BorderLayout.CENTER);
        regJournalISSNLabelPanel.add(filler31, java.awt.BorderLayout.EAST);

        regJournalISSNPanel.add(regJournalISSNLabelPanel, java.awt.BorderLayout.WEST);

        regJournalISSNTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalISSNTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regJournalISSNPanel.add(regJournalISSNTextField, java.awt.BorderLayout.CENTER);
        regJournalISSNPanel.add(filler32, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalISSNPanel);

        regJournalEmailPanel.setBackground(Theme.getBgColor());
        regJournalEmailPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalEmailPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalEmailPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalEmailPanel.setLayout(new java.awt.BorderLayout());

        regJournalEmailLabelPanel.setBackground(Theme.getBgColor());
        regJournalEmailLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalEmailLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalEmailLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalEmailLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalEmailLabel.setText("Email:");
        regJournalEmailLabelPanel.add(regJournalEmailLabel, java.awt.BorderLayout.CENTER);
        regJournalEmailLabelPanel.add(filler16, java.awt.BorderLayout.EAST);

        regJournalEmailPanel.add(regJournalEmailLabelPanel, java.awt.BorderLayout.WEST);

        regJournalEmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalEmailTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regJournalEmailPanel.add(regJournalEmailTextField, java.awt.BorderLayout.CENTER);
        regJournalEmailPanel.add(filler17, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalEmailPanel);

        regJournalPasswordPanel.setBackground(Theme.getBgColor());
        regJournalPasswordPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalPasswordPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalPasswordPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalPasswordPanel.setLayout(new java.awt.BorderLayout());

        regJournalPasswordLabelPanel.setBackground(Theme.getBgColor());
        regJournalPasswordLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalPasswordLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalPasswordLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalPasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalPasswordLabel.setText("Password:");
        regJournalPasswordLabelPanel.add(regJournalPasswordLabel, java.awt.BorderLayout.CENTER);
        regJournalPasswordLabelPanel.add(filler18, java.awt.BorderLayout.EAST);

        regJournalPasswordPanel.add(regJournalPasswordLabelPanel, java.awt.BorderLayout.WEST);

        regJournalPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalPasswordPanel.add(regJournalPasswordField, java.awt.BorderLayout.CENTER);
        regJournalPasswordPanel.add(filler19, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalPasswordPanel);

        regJournalRePasswordPanel.setBackground(Theme.getBgColor());
        regJournalRePasswordPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalRePasswordPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalRePasswordPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalRePasswordPanel.setLayout(new java.awt.BorderLayout());

        regJournalRePasswordLabelPanel.setBackground(Theme.getBgColor());
        regJournalRePasswordLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalRePasswordLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalRePasswordLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalRePasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalRePasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalRePasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalRePasswordLabel.setText("Confirm password:");
        regJournalRePasswordLabelPanel.add(regJournalRePasswordLabel, java.awt.BorderLayout.CENTER);
        regJournalRePasswordLabelPanel.add(filler20, java.awt.BorderLayout.EAST);

        regJournalRePasswordPanel.add(regJournalRePasswordLabelPanel, java.awt.BorderLayout.WEST);

        regJournalRePasswordField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalRePasswordPanel.add(regJournalRePasswordField, java.awt.BorderLayout.CENTER);
        regJournalRePasswordPanel.add(filler21, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalRePasswordPanel);

        regJournalUniversityPanel.setBackground(Theme.getBgColor());
        regJournalUniversityPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalUniversityPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalUniversityPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalUniversityPanel.setLayout(new java.awt.BorderLayout());

        regJournalUniversityLabelPanel.setBackground(Theme.getBgColor());
        regJournalUniversityLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalUniversityLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalUniversityLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalUniversityLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalUniversityLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalUniversityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalUniversityLabel.setText("University:");
        regJournalUniversityLabelPanel.add(regJournalUniversityLabel, java.awt.BorderLayout.CENTER);
        regJournalUniversityLabelPanel.add(filler22, java.awt.BorderLayout.EAST);

        regJournalUniversityPanel.add(regJournalUniversityLabelPanel, java.awt.BorderLayout.WEST);

        regJournalUniversityTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalUniversityTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regJournalUniversityPanel.add(regJournalUniversityTextField, java.awt.BorderLayout.CENTER);
        regJournalUniversityPanel.add(filler23, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalUniversityPanel);

        regJournalTitlePanel.setBackground(Theme.getBgColor());
        regJournalTitlePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalTitlePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalTitlePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalTitlePanel.setLayout(new java.awt.BorderLayout());

        regJournalTitleLabelPanel.setBackground(Theme.getBgColor());
        regJournalTitleLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalTitleLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalTitleLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalTitleLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalTitleLabel.setText("Title:");
        regJournalTitleLabelPanel.add(regJournalTitleLabel, java.awt.BorderLayout.CENTER);
        regJournalTitleLabelPanel.add(filler29, java.awt.BorderLayout.EAST);

        regJournalTitlePanel.add(regJournalTitleLabelPanel, java.awt.BorderLayout.WEST);

        regJournalTitleComboBox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalTitleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prof", "Dr", "Mr", "Ms" }));
        regJournalTitlePanel.add(regJournalTitleComboBox, java.awt.BorderLayout.CENTER);
        regJournalTitlePanel.add(filler30, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalTitlePanel);

        regJournalForenamePanel.setBackground(Theme.getBgColor());
        regJournalForenamePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalForenamePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalForenamePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalForenamePanel.setLayout(new java.awt.BorderLayout());

        regJournalForenameLabelPanel.setBackground(Theme.getBgColor());
        regJournalForenameLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalForenameLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalForenameLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalForenameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalForenameLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalForenameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalForenameLabel.setText("Forename:");
        regJournalForenameLabelPanel.add(regJournalForenameLabel, java.awt.BorderLayout.CENTER);
        regJournalForenameLabelPanel.add(filler24, java.awt.BorderLayout.EAST);

        regJournalForenamePanel.add(regJournalForenameLabelPanel, java.awt.BorderLayout.WEST);

        regJournalForenameTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalForenameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regJournalForenamePanel.add(regJournalForenameTextField, java.awt.BorderLayout.CENTER);
        regJournalForenamePanel.add(filler25, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalForenamePanel);

        regJournalSurnamePanel.setBackground(Theme.getBgColor());
        regJournalSurnamePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regJournalSurnamePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regJournalSurnamePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regJournalSurnamePanel.setLayout(new java.awt.BorderLayout());

        regJournalSurnameLabelPanel.setBackground(Theme.getBgColor());
        regJournalSurnameLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalSurnameLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalSurnameLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalSurnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalSurnameLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalSurnameLabel.setText("Surname:");
        regJournalSurnameLabelPanel.add(regJournalSurnameLabel, java.awt.BorderLayout.CENTER);
        regJournalSurnameLabelPanel.add(filler27, java.awt.BorderLayout.EAST);

        regJournalSurnamePanel.add(regJournalSurnameLabelPanel, java.awt.BorderLayout.WEST);

        regJournalSurnameTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalSurnameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regJournalSurnamePanel.add(regJournalSurnameTextField, java.awt.BorderLayout.CENTER);
        regJournalSurnamePanel.add(filler28, java.awt.BorderLayout.SOUTH);

        regJournalInnerPanel.add(regJournalSurnamePanel);

        regJournalMainPanel.add(regJournalInnerPanel, java.awt.BorderLayout.CENTER);
        regJournalMainPanel.add(filler2, java.awt.BorderLayout.NORTH);
        regJournalMainPanel.add(filler3, java.awt.BorderLayout.SOUTH);
        regJournalMainPanel.add(filler13, java.awt.BorderLayout.WEST);
        regJournalMainPanel.add(filler14, java.awt.BorderLayout.EAST);

        regJournalMainScrollPane.setViewportView(regJournalMainPanel);

        regJournalPanel.add(regJournalMainScrollPane, java.awt.BorderLayout.CENTER);

        regJournalBtnPanel.setBackground(Theme.getBgColor());
        regJournalBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regJournalBtnPanel.setMaximumSize(new java.awt.Dimension(100, 60));
        regJournalBtnPanel.setPreferredSize(new java.awt.Dimension(100, 60));
        regJournalBtnPanel.setLayout(new java.awt.BorderLayout());

        regJournalBtn.setBackground(Theme.getFgColor());
        regJournalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regJournalBtn.setMaximumSize(new java.awt.Dimension(100, 40));
        regJournalBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        regJournalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regJournalBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        regJournalBtn.setLayout(new java.awt.BorderLayout());

        regJournalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regJournalLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regJournalLabel.setText("Register");
        regJournalBtn.add(regJournalLabel, java.awt.BorderLayout.CENTER);

        regJournalBtnPanel.add(regJournalBtn, java.awt.BorderLayout.CENTER);
        regJournalBtnPanel.add(filler45, java.awt.BorderLayout.SOUTH);

        regJournalPanel.add(regJournalBtnPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(regJournalPanel, "regJournalPanel");

        loginPanel.setBackground(Theme.getBgColor());
        loginPanel.setLayout(new java.awt.BorderLayout());

        loginToobarPanel.setBackground(Theme.getBgColor());
        loginToobarPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        loginToobarPanel.setLayout(new javax.swing.BoxLayout(loginToobarPanel, javax.swing.BoxLayout.LINE_AXIS));

        loginbackBtn.setBackground(Theme.getFgColor());
        loginbackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbackBtn.setMaximumSize(new java.awt.Dimension(60, 30));
        loginbackBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        loginbackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginbackBtn.setLayout(new java.awt.BorderLayout());

        regJournalbackLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regJournalbackLabel1.setForeground(new java.awt.Color(255, 255, 255));
        regJournalbackLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regJournalbackLabel1.setText("< Back");
        loginbackBtn.add(regJournalbackLabel1, java.awt.BorderLayout.CENTER);

        loginToobarPanel.add(loginbackBtn);

        loginPanel.add(loginToobarPanel, java.awt.BorderLayout.NORTH);

        loginMainPanel.setBackground(Theme.getBgColor());
        loginMainPanel.setLayout(new java.awt.BorderLayout());

        loginInnerPanel.setBackground(Theme.getBgColor());
        loginInnerPanel.setLayout(new javax.swing.BoxLayout(loginInnerPanel, javax.swing.BoxLayout.PAGE_AXIS));

        loginRolePanel.setBackground(Theme.getBgColor());
        loginRolePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        loginRolePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        loginRolePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        loginRolePanel.setLayout(new java.awt.BorderLayout());

        loginRoleLabelPanel.setBackground(Theme.getBgColor());
        loginRoleLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        loginRoleLabelPanel.setPreferredSize(getTextfieldLabelSize());
        loginRoleLabelPanel.setLayout(new java.awt.BorderLayout());

        loginRoleLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loginRoleLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginRoleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        loginRoleLabel.setText("Login as:");
        loginRoleLabelPanel.add(loginRoleLabel, java.awt.BorderLayout.CENTER);
        loginRoleLabelPanel.add(filler26, java.awt.BorderLayout.EAST);

        loginRolePanel.add(loginRoleLabelPanel, java.awt.BorderLayout.WEST);

        loginRoleComboBox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loginRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editor", "Author", "Reviewer" }));
        loginRolePanel.add(loginRoleComboBox, java.awt.BorderLayout.CENTER);
        loginRolePanel.add(filler37, java.awt.BorderLayout.SOUTH);

        loginInnerPanel.add(loginRolePanel);

        loginEmailPanel.setBackground(Theme.getBgColor());
        loginEmailPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        loginEmailPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        loginEmailPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        loginEmailPanel.setLayout(new java.awt.BorderLayout());

        loginEmailLabelPanel.setBackground(Theme.getBgColor());
        loginEmailLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        loginEmailLabelPanel.setPreferredSize(getTextfieldLabelSize());
        loginEmailLabelPanel.setLayout(new java.awt.BorderLayout());

        loginEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loginEmailLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        loginEmailLabel.setText("Email:");
        loginEmailLabelPanel.add(loginEmailLabel, java.awt.BorderLayout.CENTER);
        loginEmailLabelPanel.add(filler38, java.awt.BorderLayout.EAST);

        loginEmailPanel.add(loginEmailLabelPanel, java.awt.BorderLayout.WEST);

        loginEmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loginEmailTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        loginEmailPanel.add(loginEmailTextField, java.awt.BorderLayout.CENTER);
        loginEmailPanel.add(filler39, java.awt.BorderLayout.SOUTH);

        loginInnerPanel.add(loginEmailPanel);

        loginPasswordPanel.setBackground(Theme.getBgColor());
        loginPasswordPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        loginPasswordPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        loginPasswordPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        loginPasswordPanel.setLayout(new java.awt.BorderLayout());

        loginPasswordLabelPanel.setBackground(Theme.getBgColor());
        loginPasswordLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        loginPasswordLabelPanel.setPreferredSize(getTextfieldLabelSize());
        loginPasswordLabelPanel.setLayout(new java.awt.BorderLayout());

        loginPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loginPasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        loginPasswordLabel.setText("Password:");
        loginPasswordLabelPanel.add(loginPasswordLabel, java.awt.BorderLayout.CENTER);
        loginPasswordLabelPanel.add(filler51, java.awt.BorderLayout.EAST);

        loginPasswordPanel.add(loginPasswordLabelPanel, java.awt.BorderLayout.WEST);

        loginPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loginPasswordPanel.add(loginPasswordField, java.awt.BorderLayout.CENTER);
        loginPasswordPanel.add(filler52, java.awt.BorderLayout.SOUTH);

        loginInnerPanel.add(loginPasswordPanel);

        loginMainPanel.add(loginInnerPanel, java.awt.BorderLayout.CENTER);
        loginMainPanel.add(filler59, java.awt.BorderLayout.NORTH);
        loginMainPanel.add(filler60, java.awt.BorderLayout.SOUTH);
        loginMainPanel.add(filler61, java.awt.BorderLayout.WEST);
        loginMainPanel.add(filler62, java.awt.BorderLayout.EAST);

        loginPanel.add(loginMainPanel, java.awt.BorderLayout.CENTER);

        loginBtnPanel.setBackground(Theme.getBgColor());
        loginBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtnPanel.setMaximumSize(new java.awt.Dimension(100, 60));
        loginBtnPanel.setLayout(new java.awt.BorderLayout());

        loginBtn.setBackground(Theme.getFgColor());
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setMaximumSize(new java.awt.Dimension(100, 40));
        loginBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginBtn.setLayout(new java.awt.BorderLayout());

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");
        loginBtn.add(loginLabel, java.awt.BorderLayout.CENTER);

        loginBtnPanel.add(loginBtn, java.awt.BorderLayout.CENTER);
        loginBtnPanel.add(filler63, java.awt.BorderLayout.SOUTH);

        loginPanel.add(loginBtnPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(loginPanel, "loginPanel");
        loginPanel.getAccessibleContext().setAccessibleName("");

        bg.add(mainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Frame size and location">
    private int frmWidth = 400;
    private int frmHeight = 300;
    
    private Dimension getFrameSize(){
        return new Dimension(frmWidth, frmHeight);
    }
    
    private Point getStartupLocation(){
        Toolkit kit = Toolkit.getDefaultToolkit();
        int screenwidth=kit.getScreenSize().width;
        int screenheight=kit.getScreenSize().height;
        int frmwidth = frmWidth;
        int frmheight = frmHeight;
        Point p = new Point(screenwidth/2-frmwidth/2, screenheight/2-frmheight/2);
        return p;
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Element size">
    private Dimension textfieldLabelSize = new Dimension(120, 100);
    private Dimension getTextfieldLabelSize(){
        return textfieldLabelSize;
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Drag & drop">
    private int dx = 0, dy = 0;
    
    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        dx = evt.getX();
        dy = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - dx, y - dy);
    }//GEN-LAST:event_bgMouseDragged

    // </editor-fold>
    
    private void loginUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginUserBtnMouseClicked
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "loginPanel");
    }//GEN-LAST:event_loginUserBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "startupPanel");
    }//GEN-LAST:event_backBtnMouseClicked

    private void loginReaderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginReaderBtnMouseClicked
        new MainFrame(this, UserRole.READER, null).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginReaderBtnMouseClicked

    private void registerAuthorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerAuthorBtnMouseClicked
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "regAuthorPanel");
    }//GEN-LAST:event_registerAuthorBtnMouseClicked

    private void registerJournalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerJournalBtnMouseClicked
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "regJournalPanel");
    }//GEN-LAST:event_registerJournalBtnMouseClicked

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        Theme.resetBackground((JPanel)evt.getSource());
    }//GEN-LAST:event_btnMouseExited

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        Theme.highlightBackground((JPanel)evt.getSource());
    }//GEN-LAST:event_btnMouseEntered

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void regJournalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regJournalBtnMouseClicked
        // TODO : Register a new journal
    }//GEN-LAST:event_regJournalBtnMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO : Login
    }//GEN-LAST:event_loginBtnMouseClicked

    private void regAuthorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regAuthorBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_regAuthorBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel closeBtn;
    private javax.swing.JLabel closeLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler30;
    private javax.swing.Box.Filler filler31;
    private javax.swing.Box.Filler filler32;
    private javax.swing.Box.Filler filler37;
    private javax.swing.Box.Filler filler38;
    private javax.swing.Box.Filler filler39;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler45;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler51;
    private javax.swing.Box.Filler filler52;
    private javax.swing.Box.Filler filler59;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler60;
    private javax.swing.Box.Filler filler61;
    private javax.swing.Box.Filler filler62;
    private javax.swing.Box.Filler filler63;
    private javax.swing.Box.Filler filler66;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JPanel loginBtnPanel;
    private javax.swing.JLabel loginEmailLabel;
    private javax.swing.JPanel loginEmailLabelPanel;
    private javax.swing.JPanel loginEmailPanel;
    private javax.swing.JTextField loginEmailTextField;
    private javax.swing.JPanel loginInnerPanel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginMainPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JPanel loginPasswordLabelPanel;
    private javax.swing.JPanel loginPasswordPanel;
    private javax.swing.JPanel loginReaderBtn;
    private javax.swing.JLabel loginReaderLabelBot;
    private javax.swing.JLabel loginReaderLabelTop;
    private javax.swing.JComboBox<String> loginRoleComboBox;
    private javax.swing.JLabel loginRoleLabel;
    private javax.swing.JPanel loginRoleLabelPanel;
    private javax.swing.JPanel loginRolePanel;
    private javax.swing.JPanel loginSelPanel;
    private javax.swing.JPanel loginToobarPanel;
    private javax.swing.JPanel loginUserBtn;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JPanel loginbackBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel regAuthorBackBtn;
    private javax.swing.JLabel regAuthorBackLabel;
    private javax.swing.JPanel regAuthorBtn;
    private javax.swing.JPanel regAuthorBtnPanel;
    private javax.swing.JLabel regAuthorLabel;
    private javax.swing.JPanel regAuthorPanel;
    private javax.swing.JPanel regAuthorToobarPanel;
    private javax.swing.JPanel regJournalBtn;
    private javax.swing.JPanel regJournalBtnPanel;
    private javax.swing.JLabel regJournalEmailLabel;
    private javax.swing.JPanel regJournalEmailLabelPanel;
    private javax.swing.JPanel regJournalEmailPanel;
    private javax.swing.JTextField regJournalEmailTextField;
    private javax.swing.JLabel regJournalForenameLabel;
    private javax.swing.JPanel regJournalForenameLabelPanel;
    private javax.swing.JPanel regJournalForenamePanel;
    private javax.swing.JTextField regJournalForenameTextField;
    private javax.swing.JLabel regJournalISSNLabel;
    private javax.swing.JPanel regJournalISSNLabelPanel;
    private javax.swing.JPanel regJournalISSNPanel;
    private javax.swing.JTextField regJournalISSNTextField;
    private javax.swing.JPanel regJournalInnerPanel;
    private javax.swing.JLabel regJournalJournalNameLabel;
    private javax.swing.JPanel regJournalJournalNameLabelPanel;
    private javax.swing.JPanel regJournalJournalNamePanel;
    private javax.swing.JTextField regJournalJournalNameTextField;
    private javax.swing.JLabel regJournalLabel;
    private javax.swing.JPanel regJournalMainPanel;
    private javax.swing.JScrollPane regJournalMainScrollPane;
    private javax.swing.JPanel regJournalPanel;
    private javax.swing.JPasswordField regJournalPasswordField;
    private javax.swing.JLabel regJournalPasswordLabel;
    private javax.swing.JPanel regJournalPasswordLabelPanel;
    private javax.swing.JPanel regJournalPasswordPanel;
    private javax.swing.JPasswordField regJournalRePasswordField;
    private javax.swing.JLabel regJournalRePasswordLabel;
    private javax.swing.JPanel regJournalRePasswordLabelPanel;
    private javax.swing.JPanel regJournalRePasswordPanel;
    private javax.swing.JLabel regJournalSurnameLabel;
    private javax.swing.JPanel regJournalSurnameLabelPanel;
    private javax.swing.JPanel regJournalSurnamePanel;
    private javax.swing.JTextField regJournalSurnameTextField;
    private javax.swing.JComboBox<String> regJournalTitleComboBox;
    private javax.swing.JLabel regJournalTitleLabel;
    private javax.swing.JPanel regJournalTitleLabelPanel;
    private javax.swing.JPanel regJournalTitlePanel;
    private javax.swing.JPanel regJournalToobarPanel;
    private javax.swing.JLabel regJournalUniversityLabel;
    private javax.swing.JPanel regJournalUniversityLabelPanel;
    private javax.swing.JPanel regJournalUniversityPanel;
    private javax.swing.JTextField regJournalUniversityTextField;
    private javax.swing.JPanel regJournalbackBtn;
    private javax.swing.JLabel regJournalbackLabel;
    private javax.swing.JLabel regJournalbackLabel1;
    private javax.swing.JPanel registerAuthorBtn;
    private javax.swing.JLabel registerAuthorLabel;
    private com.com2008.journalmanagementsystem.frame.RegisterPanel registerAuthorPanel;
    private javax.swing.JPanel registerJournalBtn;
    private javax.swing.JLabel registerJournalLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPanel selePanel;
    private javax.swing.JPanel startupPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel welLabel;
    // End of variables declaration//GEN-END:variables
}
