/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

/**
 *
 * @author boxuanshan
 */
public class ProgressManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProgressManagementSystem
     */
    public ProgressManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        journalComboBox = new javax.swing.JComboBox<>();
        leftPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        articlesScrollPane1 = new javax.swing.JScrollPane();
        articlesList = new javax.swing.JList<>();
        rightPanel = new javax.swing.JPanel();
        publishBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        journalComboBox.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        journalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Journal 1", "Journal 2", "Journal 3", "Journal 4" }));
        add(journalComboBox, java.awt.BorderLayout.NORTH);

        leftPanel.setLayout(new java.awt.BorderLayout());

        infoLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        infoLabel.setText("Vol. xx, Edition yy.  Article count: 5");
        leftPanel.add(infoLabel, java.awt.BorderLayout.NORTH);

        articlesList.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        articlesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Article 1", "Article 2", "Article 3", "Article 4", "Article 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        articlesScrollPane1.setViewportView(articlesList);

        leftPanel.add(articlesScrollPane1, java.awt.BorderLayout.CENTER);

        add(leftPanel, java.awt.BorderLayout.CENTER);

        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.PAGE_AXIS));

        publishBtn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        publishBtn.setText("Publish");
        rightPanel.add(publishBtn);

        add(rightPanel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> articlesList;
    private javax.swing.JScrollPane articlesScrollPane1;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JComboBox<String> journalComboBox;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton publishBtn;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
