/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.sql.SQLException;
import java.util.List;

import javax.swing.tree.DefaultMutableTreeNode;

import com.com2008.journalmanagementsystem.model.*;
import com.com2008.journalmanagementsystem.util.database.Database;

/**
 *
 * @author Xuan
 */
public class ReaderPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReaderPanel
     */
    public ReaderPanel() {
        initComponents();

        articalOutterPanel.removeAll();

        try {
            DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("Journals");
            List<Journal> jouranls = Database.read("Journal", new Journal());
            for(Journal journal : jouranls){
                String issn = journal.getIssn();
                DefaultMutableTreeNode journalNode = new DefaultMutableTreeNode(journal);
                List<Edition> editions = Database.read("Edition", new Edition(issn, null, null));
                for(Edition edition : editions){
                    int volume = edition.getVolume();
                    int ed = edition.getEdition();
                    DefaultMutableTreeNode editionNode = new DefaultMutableTreeNode(edition);
                    List<Article> articles = Database.read("Article", new Article(issn, null, volume, ed));
                    for(Article article : articles){
                        String submissionID = article.getSubmissionID();
                        Submission submission = Database.read("Submission", new Submission(issn, submissionID, null, null, null, null, null, null, null)).get(0);
                        DefaultMutableTreeNode articalNode = new DefaultMutableTreeNode(submission);
                        editionNode.add(articalNode);
                    }
                    journalNode.add(editionNode);
                }
                rootNode.add(journalNode);
            }
            journalTree.setModel(new javax.swing.tree.DefaultTreeModel(rootNode));
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        journalScrollPane = new javax.swing.JScrollPane();
        journalTree = new javax.swing.JTree();
        articalOutterPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        journalTree.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Journals");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Journal1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vol.1");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition1");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition2");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vol.2");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition1");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vol.3");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition1");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Journal2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vol.1");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition1");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition2");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition3");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vol.2");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition1");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Journal3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Vol.1");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Edition1");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        journalTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        journalTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                journalTreeValueChanged(evt);
            }
        });
        journalScrollPane.setViewportView(journalTree);

        jSplitPane1.setLeftComponent(journalScrollPane);

        articalOutterPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(articalOutterPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void journalTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_journalTreeValueChanged
        DefaultMutableTreeNode lastNode = (DefaultMutableTreeNode)evt.getPath().getLastPathComponent();
        Object userObject = lastNode.getUserObject();
        if(userObject.getClass() == Submission.class){
            Submission submission = (Submission)userObject;
            articalOutterPanel.removeAll();
            articalOutterPanel.add(new ArticlePanel(submission), java.awt.BorderLayout.CENTER);
            articalOutterPanel.revalidate();
        }
    }//GEN-LAST:event_journalTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel articalOutterPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JScrollPane journalScrollPane;
    private javax.swing.JTree journalTree;
    // End of variables declaration//GEN-END:variables
}
