/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.awt.Dimension;

/**
 *
 * @author Xuan
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form registerPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regMainScrollPane = new javax.swing.JScrollPane();
        regMainPanel = new javax.swing.JPanel();
        regInnerPanel = new javax.swing.JPanel();
        regEmailPanel = new javax.swing.JPanel();
        regJournalEmailLabelPanel = new javax.swing.JPanel();
        regJournalEmailLabel = new javax.swing.JLabel();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalEmailTextField = new javax.swing.JTextField();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regPasswordPanel = new javax.swing.JPanel();
        regJournalPasswordLabelPanel = new javax.swing.JPanel();
        regJournalPasswordLabel = new javax.swing.JLabel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalPasswordField = new javax.swing.JPasswordField();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regRePasswordPanel = new javax.swing.JPanel();
        regJournalRePasswordLabelPanel = new javax.swing.JPanel();
        regJournalRePasswordLabel = new javax.swing.JLabel();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalRePasswordField = new javax.swing.JPasswordField();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regUniversityPanel = new javax.swing.JPanel();
        regJournalUniversityLabelPanel = new javax.swing.JPanel();
        regJournalUniversityLabel = new javax.swing.JLabel();
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalUniversityTextField = new javax.swing.JTextField();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regTitlePanel = new javax.swing.JPanel();
        regJournalTitleLabelPanel = new javax.swing.JPanel();
        regJournalTitleLabel = new javax.swing.JLabel();
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalTitleComboBox = new javax.swing.JComboBox<>();
        filler30 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regForenamePanel = new javax.swing.JPanel();
        regJournalForenameLabelPanel = new javax.swing.JPanel();
        regJournalForenameLabel = new javax.swing.JLabel();
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalForenameTextField = new javax.swing.JTextField();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        regSurnamePanel = new javax.swing.JPanel();
        regJournalSurnameLabelPanel = new javax.swing.JPanel();
        regJournalSurnameLabel = new javax.swing.JLabel();
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        regJournalSurnameTextField = new javax.swing.JTextField();
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setLayout(new java.awt.BorderLayout());

        regMainScrollPane.setBackground(Theme.getBgColor());
        regMainScrollPane.setBorder(null);

        regMainPanel.setBackground(Theme.getBgColor());
        regMainPanel.setLayout(new java.awt.BorderLayout());

        regInnerPanel.setBackground(Theme.getBgColor());
        regInnerPanel.setLayout(new javax.swing.BoxLayout(regInnerPanel, javax.swing.BoxLayout.PAGE_AXIS));

        regEmailPanel.setBackground(Theme.getBgColor());
        regEmailPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regEmailPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regEmailPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regEmailPanel.setLayout(new java.awt.BorderLayout());

        regJournalEmailLabelPanel.setBackground(Theme.getBgColor());
        regJournalEmailLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalEmailLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalEmailLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalEmailLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalEmailLabel.setText("Email:");
        regJournalEmailLabelPanel.add(regJournalEmailLabel, java.awt.BorderLayout.CENTER);
        regJournalEmailLabelPanel.add(filler16, java.awt.BorderLayout.EAST);

        regEmailPanel.add(regJournalEmailLabelPanel, java.awt.BorderLayout.WEST);

        regJournalEmailTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regEmailPanel.add(regJournalEmailTextField, java.awt.BorderLayout.CENTER);
        regEmailPanel.add(filler17, java.awt.BorderLayout.SOUTH);

        regInnerPanel.add(regEmailPanel);

        regPasswordPanel.setBackground(Theme.getBgColor());
        regPasswordPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regPasswordPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regPasswordPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regPasswordPanel.setLayout(new java.awt.BorderLayout());

        regJournalPasswordLabelPanel.setBackground(Theme.getBgColor());
        regJournalPasswordLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalPasswordLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalPasswordLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalPasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalPasswordLabel.setText("Password:");
        regJournalPasswordLabelPanel.add(regJournalPasswordLabel, java.awt.BorderLayout.CENTER);
        regJournalPasswordLabelPanel.add(filler18, java.awt.BorderLayout.EAST);

        regPasswordPanel.add(regJournalPasswordLabelPanel, java.awt.BorderLayout.WEST);
        regPasswordPanel.add(regJournalPasswordField, java.awt.BorderLayout.CENTER);
        regPasswordPanel.add(filler19, java.awt.BorderLayout.SOUTH);

        regInnerPanel.add(regPasswordPanel);

        regRePasswordPanel.setBackground(Theme.getBgColor());
        regRePasswordPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regRePasswordPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regRePasswordPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regRePasswordPanel.setLayout(new java.awt.BorderLayout());

        regJournalRePasswordLabelPanel.setBackground(Theme.getBgColor());
        regJournalRePasswordLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalRePasswordLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalRePasswordLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalRePasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalRePasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalRePasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalRePasswordLabel.setText("Confirm password:");
        regJournalRePasswordLabelPanel.add(regJournalRePasswordLabel, java.awt.BorderLayout.CENTER);
        regJournalRePasswordLabelPanel.add(filler20, java.awt.BorderLayout.EAST);

        regRePasswordPanel.add(regJournalRePasswordLabelPanel, java.awt.BorderLayout.WEST);
        regRePasswordPanel.add(regJournalRePasswordField, java.awt.BorderLayout.CENTER);
        regRePasswordPanel.add(filler21, java.awt.BorderLayout.SOUTH);

        regInnerPanel.add(regRePasswordPanel);

        regUniversityPanel.setBackground(Theme.getBgColor());
        regUniversityPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regUniversityPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regUniversityPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regUniversityPanel.setLayout(new java.awt.BorderLayout());

        regJournalUniversityLabelPanel.setBackground(Theme.getBgColor());
        regJournalUniversityLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalUniversityLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalUniversityLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalUniversityLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalUniversityLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalUniversityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalUniversityLabel.setText("University:");
        regJournalUniversityLabelPanel.add(regJournalUniversityLabel, java.awt.BorderLayout.CENTER);
        regJournalUniversityLabelPanel.add(filler22, java.awt.BorderLayout.EAST);

        regUniversityPanel.add(regJournalUniversityLabelPanel, java.awt.BorderLayout.WEST);

        regJournalUniversityTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regUniversityPanel.add(regJournalUniversityTextField, java.awt.BorderLayout.CENTER);
        regUniversityPanel.add(filler23, java.awt.BorderLayout.SOUTH);

        regInnerPanel.add(regUniversityPanel);

        regTitlePanel.setBackground(Theme.getBgColor());
        regTitlePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regTitlePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regTitlePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regTitlePanel.setLayout(new java.awt.BorderLayout());

        regJournalTitleLabelPanel.setBackground(Theme.getBgColor());
        regJournalTitleLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalTitleLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalTitleLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalTitleLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalTitleLabel.setText("Title:");
        regJournalTitleLabelPanel.add(regJournalTitleLabel, java.awt.BorderLayout.CENTER);
        regJournalTitleLabelPanel.add(filler29, java.awt.BorderLayout.EAST);

        regTitlePanel.add(regJournalTitleLabelPanel, java.awt.BorderLayout.WEST);

        regJournalTitleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prof", "Dr", "Mr", "Ms" }));
        regTitlePanel.add(regJournalTitleComboBox, java.awt.BorderLayout.CENTER);
        regTitlePanel.add(filler30, java.awt.BorderLayout.SOUTH);

        regInnerPanel.add(regTitlePanel);

        regForenamePanel.setBackground(Theme.getBgColor());
        regForenamePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regForenamePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regForenamePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regForenamePanel.setLayout(new java.awt.BorderLayout());

        regJournalForenameLabelPanel.setBackground(Theme.getBgColor());
        regJournalForenameLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalForenameLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalForenameLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalForenameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalForenameLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalForenameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalForenameLabel.setText("Forename:");
        regJournalForenameLabelPanel.add(regJournalForenameLabel, java.awt.BorderLayout.CENTER);
        regJournalForenameLabelPanel.add(filler24, java.awt.BorderLayout.EAST);

        regForenamePanel.add(regJournalForenameLabelPanel, java.awt.BorderLayout.WEST);

        regJournalForenameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regForenamePanel.add(regJournalForenameTextField, java.awt.BorderLayout.CENTER);
        regForenamePanel.add(filler25, java.awt.BorderLayout.SOUTH);

        regInnerPanel.add(regForenamePanel);

        regSurnamePanel.setBackground(Theme.getBgColor());
        regSurnamePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        regSurnamePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        regSurnamePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        regSurnamePanel.setLayout(new java.awt.BorderLayout());

        regJournalSurnameLabelPanel.setBackground(Theme.getBgColor());
        regJournalSurnameLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        regJournalSurnameLabelPanel.setPreferredSize(getTextfieldLabelSize());
        regJournalSurnameLabelPanel.setLayout(new java.awt.BorderLayout());

        regJournalSurnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalSurnameLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regJournalSurnameLabel.setText("Surname:");
        regJournalSurnameLabelPanel.add(regJournalSurnameLabel, java.awt.BorderLayout.CENTER);
        regJournalSurnameLabelPanel.add(filler27, java.awt.BorderLayout.EAST);

        regSurnamePanel.add(regJournalSurnameLabelPanel, java.awt.BorderLayout.WEST);

        regJournalSurnameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        regSurnamePanel.add(regJournalSurnameTextField, java.awt.BorderLayout.CENTER);
        regSurnamePanel.add(filler28, java.awt.BorderLayout.SOUTH);

        regInnerPanel.add(regSurnamePanel);

        regMainPanel.add(regInnerPanel, java.awt.BorderLayout.CENTER);
        regMainPanel.add(filler2, java.awt.BorderLayout.NORTH);
        regMainPanel.add(filler3, java.awt.BorderLayout.SOUTH);
        regMainPanel.add(filler13, java.awt.BorderLayout.WEST);
        regMainPanel.add(filler14, java.awt.BorderLayout.EAST);

        regMainScrollPane.setViewportView(regMainPanel);

        add(regMainScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Element size">
    private Dimension textfieldLabelSize = new Dimension(120, 100);
    private Dimension getTextfieldLabelSize(){
        return textfieldLabelSize;
    }
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler30;
    private javax.swing.JPanel regEmailPanel;
    private javax.swing.JPanel regForenamePanel;
    private javax.swing.JPanel regInnerPanel;
    private javax.swing.JLabel regJournalEmailLabel;
    private javax.swing.JPanel regJournalEmailLabelPanel;
    private javax.swing.JTextField regJournalEmailTextField;
    private javax.swing.JLabel regJournalForenameLabel;
    private javax.swing.JPanel regJournalForenameLabelPanel;
    private javax.swing.JTextField regJournalForenameTextField;
    private javax.swing.JPasswordField regJournalPasswordField;
    private javax.swing.JLabel regJournalPasswordLabel;
    private javax.swing.JPanel regJournalPasswordLabelPanel;
    private javax.swing.JPasswordField regJournalRePasswordField;
    private javax.swing.JLabel regJournalRePasswordLabel;
    private javax.swing.JPanel regJournalRePasswordLabelPanel;
    private javax.swing.JLabel regJournalSurnameLabel;
    private javax.swing.JPanel regJournalSurnameLabelPanel;
    private javax.swing.JTextField regJournalSurnameTextField;
    private javax.swing.JComboBox<String> regJournalTitleComboBox;
    private javax.swing.JLabel regJournalTitleLabel;
    private javax.swing.JPanel regJournalTitleLabelPanel;
    private javax.swing.JLabel regJournalUniversityLabel;
    private javax.swing.JPanel regJournalUniversityLabelPanel;
    private javax.swing.JTextField regJournalUniversityTextField;
    private javax.swing.JPanel regMainPanel;
    private javax.swing.JScrollPane regMainScrollPane;
    private javax.swing.JPanel regPasswordPanel;
    private javax.swing.JPanel regRePasswordPanel;
    private javax.swing.JPanel regSurnamePanel;
    private javax.swing.JPanel regTitlePanel;
    private javax.swing.JPanel regUniversityPanel;
    // End of variables declaration//GEN-END:variables
}
