/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.com2008.journalmanagementsystem.model.Account;
import com.com2008.journalmanagementsystem.util.database.Database;

/**
 *
 * @author boxuanshan
 */
public class RegisterDialog extends javax.swing.JDialog {

    /**
     * Creates new form RegisterDialog
     */
    public RegisterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public RegisterDialog(java.awt.Frame parent, boolean modal, String email) {
        super(parent, modal);
        initComponents();
        registerPanel.setEmail(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerPanel = new com.com2008.journalmanagementsystem.frame.RegisterPanel();
        regAuthorBtnPanel = new javax.swing.JPanel();
        registerBtn = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        filler66 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(registerPanel, java.awt.BorderLayout.CENTER);

        regAuthorBtnPanel.setBackground(Theme.getBgColor());
        regAuthorBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regAuthorBtnPanel.setMaximumSize(new java.awt.Dimension(100, 60));
        regAuthorBtnPanel.setLayout(new java.awt.BorderLayout());

        registerBtn.setBackground(Theme.getFgColor());
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.setMaximumSize(new java.awt.Dimension(100, 40));
        registerBtn.setPreferredSize(new java.awt.Dimension(100, 40));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        registerBtn.setLayout(new java.awt.BorderLayout());

        registerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(204, 204, 204));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Register");
        registerBtn.add(registerLabel, java.awt.BorderLayout.CENTER);

        regAuthorBtnPanel.add(registerBtn, java.awt.BorderLayout.CENTER);
        regAuthorBtnPanel.add(filler66, java.awt.BorderLayout.SOUTH);

        getContentPane().add(regAuthorBtnPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean registered = false;
    private Account account;
    private String hashedPassword;

    public boolean isRegistered() {
        return registered;
    }

    public void setRegistered(boolean registered) {
        this.registered = registered;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public String getHashedPassword() {
        return hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        if (!registerPanel.verify())
            return;

        account = registerPanel.getRegInfo();
        hashedPassword = registerPanel.getHashedPassword();

        try {
            if(Database.read("Account", new Account(account.getEmail(), null, null, null, null)).size() > 0){
                JOptionPane.showMessageDialog(null, "Email already exists.", "Register", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        registered = true;
        this.setVisible(false);
    }//GEN-LAST:event_registerBtnMouseClicked

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        Theme.highlightBackground((JPanel) evt.getSource());
    }//GEN-LAST:event_btnMouseEntered

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        Theme.resetBackground((JPanel) evt.getSource());
    }//GEN-LAST:event_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterDialog dialog = new RegisterDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler66;
    private javax.swing.JPanel regAuthorBtnPanel;
    private javax.swing.JPanel registerBtn;
    private javax.swing.JLabel registerLabel;
    private com.com2008.journalmanagementsystem.frame.RegisterPanel registerPanel;
    // End of variables declaration//GEN-END:variables
}
