/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

import java.awt.Dimension;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

/**
 *
 * @author Xuan
 */
public class RegisterJournalPanel extends javax.swing.JPanel {

    /**
     * Creates new form registerPanel
     */
    public RegisterJournalPanel() {
        initComponents();
    }

    public String getISSN(){
        return issnTextField.getText();
    }

    public String getJournalName(){
        return journalNameTextField.getText();
    }

    public boolean verify(){
        String issn = issnTextField.getText();
        String journalName = journalNameTextField.getText();

        if(issn.isEmpty() || journalName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please complete all the fileds.", "Register", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        String patternString = "^ISSN [0-9]{4}-[0-9]{3}[0-9X]$";
        Pattern pattern = Pattern.compile(patternString);
        Matcher matcher = pattern.matcher(issn);
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(null, "Invalid ISSN.", "Register", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        innerPanel = new javax.swing.JPanel();
        issnPanel = new javax.swing.JPanel();
        issnLabelPanel = new javax.swing.JPanel();
        issnLabel = new javax.swing.JLabel();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        issnTextField = new javax.swing.JTextField();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        journalNamePanel = new javax.swing.JPanel();
        journalNameLabelPanel = new javax.swing.JPanel();
        journalNameLabel = new javax.swing.JLabel();
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        journalNameTextField = new javax.swing.JTextField();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setMinimumSize(new java.awt.Dimension(21, 82));
        setLayout(new java.awt.BorderLayout());

        mainScrollPane.setBackground(Theme.getBgColor());
        mainScrollPane.setBorder(null);

        mainPanel.setBackground(Theme.getBgColor());
        mainPanel.setLayout(new java.awt.BorderLayout());

        innerPanel.setBackground(Theme.getBgColor());
        innerPanel.setLayout(new javax.swing.BoxLayout(innerPanel, javax.swing.BoxLayout.PAGE_AXIS));

        issnPanel.setBackground(Theme.getBgColor());
        issnPanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        issnPanel.setMinimumSize(new java.awt.Dimension(0, 31));
        issnPanel.setPreferredSize(new java.awt.Dimension(120, 31));
        issnPanel.setLayout(new java.awt.BorderLayout());

        issnLabelPanel.setBackground(Theme.getBgColor());
        issnLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        issnLabelPanel.setPreferredSize(getTextfieldLabelSize());
        issnLabelPanel.setLayout(new java.awt.BorderLayout());

        issnLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        issnLabel.setForeground(new java.awt.Color(204, 204, 204));
        issnLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        issnLabel.setText("ISSN:");
        issnLabelPanel.add(issnLabel, java.awt.BorderLayout.CENTER);
        issnLabelPanel.add(filler16, java.awt.BorderLayout.EAST);

        issnPanel.add(issnLabelPanel, java.awt.BorderLayout.WEST);

        issnTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        issnTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        issnPanel.add(issnTextField, java.awt.BorderLayout.CENTER);
        issnPanel.add(filler17, java.awt.BorderLayout.SOUTH);

        innerPanel.add(issnPanel);

        journalNamePanel.setBackground(Theme.getBgColor());
        journalNamePanel.setMaximumSize(new java.awt.Dimension(2147483647, 31));
        journalNamePanel.setMinimumSize(new java.awt.Dimension(0, 31));
        journalNamePanel.setPreferredSize(new java.awt.Dimension(120, 31));
        journalNamePanel.setLayout(new java.awt.BorderLayout());

        journalNameLabelPanel.setBackground(Theme.getBgColor());
        journalNameLabelPanel.setMinimumSize(new java.awt.Dimension(110, 16));
        journalNameLabelPanel.setPreferredSize(getTextfieldLabelSize());
        journalNameLabelPanel.setLayout(new java.awt.BorderLayout());

        journalNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        journalNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        journalNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        journalNameLabel.setText("Journal name:");
        journalNameLabelPanel.add(journalNameLabel, java.awt.BorderLayout.CENTER);
        journalNameLabelPanel.add(filler22, java.awt.BorderLayout.EAST);

        journalNamePanel.add(journalNameLabelPanel, java.awt.BorderLayout.WEST);

        journalNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        journalNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        journalNamePanel.add(journalNameTextField, java.awt.BorderLayout.CENTER);
        journalNamePanel.add(filler23, java.awt.BorderLayout.SOUTH);

        innerPanel.add(journalNamePanel);

        mainPanel.add(innerPanel, java.awt.BorderLayout.CENTER);
        mainPanel.add(filler2, java.awt.BorderLayout.NORTH);
        mainPanel.add(filler3, java.awt.BorderLayout.SOUTH);
        mainPanel.add(filler13, java.awt.BorderLayout.WEST);
        mainPanel.add(filler14, java.awt.BorderLayout.EAST);

        mainScrollPane.setViewportView(mainPanel);

        add(mainScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Element size">
    private Dimension textfieldLabelSize = new Dimension(120, 100);
    private Dimension getTextfieldLabelSize(){
        return textfieldLabelSize;
    }
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JLabel issnLabel;
    private javax.swing.JPanel issnLabelPanel;
    private javax.swing.JPanel issnPanel;
    private javax.swing.JTextField issnTextField;
    private javax.swing.JLabel journalNameLabel;
    private javax.swing.JPanel journalNameLabelPanel;
    private javax.swing.JPanel journalNamePanel;
    private javax.swing.JTextField journalNameTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    // End of variables declaration//GEN-END:variables
}
