/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem.frame;

/**
 *
 * @author boxuanshan
 */
public class StaffManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form StaffManagementPanel
     */
    public StaffManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        journalComboBox = new javax.swing.JComboBox<>();
        leftPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        editorsScrollPane1 = new javax.swing.JScrollPane();
        editorsList = new javax.swing.JList<>();
        rightPanel = new javax.swing.JPanel();
        addStaffBtn = new javax.swing.JButton();
        removeStaffBtn = new javax.swing.JButton();
        transferCheifBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        journalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Journal 1", "Journal 2", "Journal 3", "Journal 4" }));
        add(journalComboBox, java.awt.BorderLayout.NORTH);

        leftPanel.setLayout(new java.awt.BorderLayout());

        searchTextField.setText("Search bar");
        leftPanel.add(searchTextField, java.awt.BorderLayout.NORTH);

        editorsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Editor 1", "Editor 2", "Editor 3", "Editor 4", "Editor 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        editorsScrollPane1.setViewportView(editorsList);

        leftPanel.add(editorsScrollPane1, java.awt.BorderLayout.CENTER);

        add(leftPanel, java.awt.BorderLayout.CENTER);

        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.PAGE_AXIS));

        addStaffBtn.setText("Add staff");
        rightPanel.add(addStaffBtn);

        removeStaffBtn.setText("Remove staff");
        rightPanel.add(removeStaffBtn);

        transferCheifBtn.setText("Transfer cheif");
        rightPanel.add(transferCheifBtn);

        add(rightPanel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffBtn;
    private javax.swing.JList<String> editorsList;
    private javax.swing.JScrollPane editorsScrollPane1;
    private javax.swing.JComboBox<String> journalComboBox;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton removeStaffBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton transferCheifBtn;
    // End of variables declaration//GEN-END:variables
}
