/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem;

/**
 *
 * @author Xuan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        titleLabel = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        closeBtn = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        startupPanel = new javax.swing.JPanel();
        selePanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        welLabel = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginSelPanel = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        loginReaderBtn = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginReaderLabel = new javax.swing.JLabel();
        loginReaderLabel1 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        loginUserBtn = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        registerPanel = new javax.swing.JPanel();
        registerReviewerBtn = new javax.swing.JPanel();
        registerReviewerLabel = new javax.swing.JLabel();
        registerJournalBtn = new javax.swing.JPanel();
        registerJournalLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        loginToobarPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        loginMainPanel = new javax.swing.JPanel();
        rolePanel = new javax.swing.JPanel();
        roleLabel = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        filler30 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler31 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler32 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        passwordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        filler33 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler34 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler35 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        loginBtnPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        filler36 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        regJournalPanel = new javax.swing.JPanel();
        regJournalToobarPanel = new javax.swing.JPanel();
        regJournalbackBtn = new javax.swing.JPanel();
        regJournalbackLabel = new javax.swing.JLabel();
        regJournalMainPanel = new javax.swing.JPanel();
        regJournalJournalNamePanel = new javax.swing.JPanel();
        regJournalJournalNameLabel = new javax.swing.JLabel();
        regJournalJournalNameTextField = new javax.swing.JTextField();
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        regJournalUsernamePanel = new javax.swing.JPanel();
        regJournalUsernameLabel = new javax.swing.JLabel();
        regJournalUsernameTextField = new javax.swing.JTextField();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        regJournalPasswordPanel = new javax.swing.JPanel();
        regJournalPasswordLabel = new javax.swing.JLabel();
        regJournalPasswordField = new javax.swing.JPasswordField();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        regJournalBtnPanel = new javax.swing.JPanel();
        regJournalBtn = new javax.swing.JPanel();
        regJournalLabel = new javax.swing.JLabel();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(getStartupLocation());
        setUndecorated(true);
        setPreferredSize(getFrameSize());
        setSize(getFrameSize());

        bg.setBackground(new java.awt.Color(54, 33, 89));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(54, 33, 89));
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        headerPanel.setLayout(new javax.swing.BoxLayout(headerPanel, javax.swing.BoxLayout.LINE_AXIS));
        headerPanel.add(filler10);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 204, 204));
        titleLabel.setText("Login");
        headerPanel.add(titleLabel);
        headerPanel.add(filler12);

        closeBtn.setBackground(new java.awt.Color(64, 43, 100));
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.setMaximumSize(new java.awt.Dimension(30, 30));
        closeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        closeBtn.setLayout(new java.awt.BorderLayout());

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("×");
        closeBtn.add(closeLabel, java.awt.BorderLayout.CENTER);

        headerPanel.add(closeBtn);

        bg.add(headerPanel, java.awt.BorderLayout.NORTH);

        mainPanel.setLayout(new java.awt.CardLayout());

        startupPanel.setLayout(new java.awt.BorderLayout());

        selePanel.setBackground(new java.awt.Color(54, 33, 89));
        selePanel.setLayout(new javax.swing.BoxLayout(selePanel, javax.swing.BoxLayout.PAGE_AXIS));
        selePanel.add(filler4);

        welLabel.setBackground(new java.awt.Color(255, 255, 255));
        welLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welLabel.setForeground(new java.awt.Color(204, 204, 204));
        welLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welLabel.setText("Welcome");
        welLabel.setAlignmentX(0.5F);
        selePanel.add(welLabel);
        selePanel.add(filler5);

        loginSelPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginSelPanel.setLayout(new javax.swing.BoxLayout(loginSelPanel, javax.swing.BoxLayout.LINE_AXIS));
        loginSelPanel.add(filler8);

        loginReaderBtn.setBackground(new java.awt.Color(64, 43, 100));
        loginReaderBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginReaderBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        loginReaderBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        loginReaderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginReaderBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginReaderBtn.setLayout(new java.awt.GridLayout(4, 1));
        loginReaderBtn.add(filler11);

        loginReaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginReaderLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginReaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginReaderLabel.setText("Enter as a");
        loginReaderBtn.add(loginReaderLabel);

        loginReaderLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginReaderLabel1.setForeground(new java.awt.Color(204, 204, 204));
        loginReaderLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginReaderLabel1.setText("Reader");
        loginReaderBtn.add(loginReaderLabel1);

        loginSelPanel.add(loginReaderBtn);
        loginSelPanel.add(filler7);

        loginUserBtn.setBackground(new java.awt.Color(64, 43, 100));
        loginUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginUserBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        loginUserBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        loginUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginUserBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginUserBtn.setLayout(new java.awt.BorderLayout());

        loginUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        loginUserLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginUserLabel.setText("Login");
        loginUserBtn.add(loginUserLabel, java.awt.BorderLayout.CENTER);

        loginSelPanel.add(loginUserBtn);
        loginSelPanel.add(filler9);

        selePanel.add(loginSelPanel);
        selePanel.add(filler6);

        startupPanel.add(selePanel, java.awt.BorderLayout.CENTER);

        registerPanel.setLayout(new java.awt.GridLayout(1, 2));

        registerReviewerBtn.setBackground(new java.awt.Color(64, 43, 100));
        registerReviewerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerReviewerBtn.setMaximumSize(new java.awt.Dimension(100, 30));
        registerReviewerBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        registerReviewerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerReviewerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        registerReviewerBtn.setLayout(new java.awt.BorderLayout());

        registerReviewerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerReviewerLabel.setForeground(new java.awt.Color(204, 204, 204));
        registerReviewerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerReviewerLabel.setText("I want to be a reviewer");
        registerReviewerBtn.add(registerReviewerLabel, java.awt.BorderLayout.CENTER);

        registerPanel.add(registerReviewerBtn);

        registerJournalBtn.setBackground(new java.awt.Color(64, 43, 100));
        registerJournalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerJournalBtn.setMaximumSize(new java.awt.Dimension(100, 30));
        registerJournalBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        registerJournalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerJournalBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        registerJournalBtn.setLayout(new java.awt.BorderLayout());

        registerJournalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerJournalLabel.setForeground(new java.awt.Color(204, 204, 204));
        registerJournalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerJournalLabel.setText("I want to register a journal");
        registerJournalBtn.add(registerJournalLabel, java.awt.BorderLayout.CENTER);

        registerPanel.add(registerJournalBtn);

        startupPanel.add(registerPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(startupPanel, "startupPanel");

        loginPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginPanel.setLayout(new java.awt.BorderLayout());

        loginToobarPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginToobarPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        loginToobarPanel.setLayout(new javax.swing.BoxLayout(loginToobarPanel, javax.swing.BoxLayout.LINE_AXIS));

        backBtn.setBackground(new java.awt.Color(64, 43, 100));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setMaximumSize(new java.awt.Dimension(60, 30));
        backBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        backBtn.setLayout(new java.awt.BorderLayout());

        backLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("< Back");
        backBtn.add(backLabel, java.awt.BorderLayout.CENTER);

        loginToobarPanel.add(backBtn);

        loginPanel.add(loginToobarPanel, java.awt.BorderLayout.NORTH);

        loginMainPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginMainPanel.setLayout(new java.awt.GridLayout(4, 1));

        rolePanel.setBackground(new java.awt.Color(54, 33, 89));
        rolePanel.setLayout(new java.awt.BorderLayout());

        roleLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(204, 204, 204));
        roleLabel.setText("                Role: ");
        rolePanel.add(roleLabel, java.awt.BorderLayout.WEST);

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editor", "Author", "Reviewer" }));
        rolePanel.add(roleComboBox, java.awt.BorderLayout.CENTER);
        rolePanel.add(filler27, java.awt.BorderLayout.NORTH);
        rolePanel.add(filler28, java.awt.BorderLayout.SOUTH);
        rolePanel.add(filler29, java.awt.BorderLayout.EAST);

        loginMainPanel.add(rolePanel);

        usernamePanel.setBackground(new java.awt.Color(54, 33, 89));
        usernamePanel.setLayout(new java.awt.BorderLayout());

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel.setText("      Username: ");
        usernamePanel.add(usernameLabel, java.awt.BorderLayout.WEST);
        usernamePanel.add(usernameTextField, java.awt.BorderLayout.CENTER);
        usernamePanel.add(filler30, java.awt.BorderLayout.NORTH);
        usernamePanel.add(filler31, java.awt.BorderLayout.SOUTH);
        usernamePanel.add(filler32, java.awt.BorderLayout.LINE_END);

        loginMainPanel.add(usernamePanel);

        passwordPanel.setBackground(new java.awt.Color(54, 33, 89));
        passwordPanel.setLayout(new java.awt.BorderLayout());

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel.setText("      Password:  ");
        passwordPanel.add(passwordLabel, java.awt.BorderLayout.WEST);
        passwordPanel.add(passwordField, java.awt.BorderLayout.CENTER);
        passwordPanel.add(filler33, java.awt.BorderLayout.NORTH);
        passwordPanel.add(filler34, java.awt.BorderLayout.SOUTH);
        passwordPanel.add(filler35, java.awt.BorderLayout.LINE_END);

        loginMainPanel.add(passwordPanel);

        loginBtnPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtnPanel.setMaximumSize(new java.awt.Dimension(100, 100));
        loginBtnPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        loginBtnPanel.setLayout(new java.awt.BorderLayout());

        loginBtn.setBackground(new java.awt.Color(64, 43, 100));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        loginBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginBtn.setLayout(new java.awt.BorderLayout());

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");
        loginBtn.add(loginLabel, java.awt.BorderLayout.CENTER);

        loginBtnPanel.add(loginBtn, java.awt.BorderLayout.CENTER);
        loginBtnPanel.add(filler36, java.awt.BorderLayout.SOUTH);

        loginMainPanel.add(loginBtnPanel);

        loginPanel.add(loginMainPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(loginPanel, "loginPanel");

        regJournalPanel.setBackground(new java.awt.Color(54, 33, 89));
        regJournalPanel.setLayout(new java.awt.BorderLayout());

        regJournalToobarPanel.setBackground(new java.awt.Color(54, 33, 89));
        regJournalToobarPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        regJournalToobarPanel.setLayout(new javax.swing.BoxLayout(regJournalToobarPanel, javax.swing.BoxLayout.LINE_AXIS));

        regJournalbackBtn.setBackground(new java.awt.Color(64, 43, 100));
        regJournalbackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regJournalbackBtn.setMaximumSize(new java.awt.Dimension(60, 30));
        regJournalbackBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        regJournalbackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        regJournalbackBtn.setLayout(new java.awt.BorderLayout());

        regJournalbackLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regJournalbackLabel.setForeground(new java.awt.Color(255, 255, 255));
        regJournalbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regJournalbackLabel.setText("< Back");
        regJournalbackBtn.add(regJournalbackLabel, java.awt.BorderLayout.CENTER);

        regJournalToobarPanel.add(regJournalbackBtn);

        regJournalPanel.add(regJournalToobarPanel, java.awt.BorderLayout.NORTH);

        regJournalMainPanel.setBackground(new java.awt.Color(54, 33, 89));
        regJournalMainPanel.setLayout(new java.awt.GridLayout(4, 1));

        regJournalJournalNamePanel.setBackground(new java.awt.Color(54, 33, 89));
        regJournalJournalNamePanel.setLayout(new java.awt.BorderLayout());

        regJournalJournalNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalJournalNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalJournalNameLabel.setText("      Journal name: ");
        regJournalJournalNamePanel.add(regJournalJournalNameLabel, java.awt.BorderLayout.WEST);
        regJournalJournalNamePanel.add(regJournalJournalNameTextField, java.awt.BorderLayout.CENTER);
        regJournalJournalNamePanel.add(filler24, java.awt.BorderLayout.NORTH);
        regJournalJournalNamePanel.add(filler25, java.awt.BorderLayout.SOUTH);
        regJournalJournalNamePanel.add(filler26, java.awt.BorderLayout.LINE_END);

        regJournalMainPanel.add(regJournalJournalNamePanel);

        regJournalUsernamePanel.setBackground(new java.awt.Color(54, 33, 89));
        regJournalUsernamePanel.setLayout(new java.awt.BorderLayout());

        regJournalUsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalUsernameLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalUsernameLabel.setText("      Username: ");
        regJournalUsernamePanel.add(regJournalUsernameLabel, java.awt.BorderLayout.WEST);
        regJournalUsernamePanel.add(regJournalUsernameTextField, java.awt.BorderLayout.CENTER);
        regJournalUsernamePanel.add(filler16, java.awt.BorderLayout.NORTH);
        regJournalUsernamePanel.add(filler18, java.awt.BorderLayout.SOUTH);
        regJournalUsernamePanel.add(filler19, java.awt.BorderLayout.LINE_END);

        regJournalMainPanel.add(regJournalUsernamePanel);

        regJournalPasswordPanel.setBackground(new java.awt.Color(54, 33, 89));
        regJournalPasswordPanel.setLayout(new java.awt.BorderLayout());

        regJournalPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        regJournalPasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalPasswordLabel.setText("      Password:  ");
        regJournalPasswordPanel.add(regJournalPasswordLabel, java.awt.BorderLayout.WEST);
        regJournalPasswordPanel.add(regJournalPasswordField, java.awt.BorderLayout.CENTER);
        regJournalPasswordPanel.add(filler20, java.awt.BorderLayout.NORTH);
        regJournalPasswordPanel.add(filler21, java.awt.BorderLayout.SOUTH);
        regJournalPasswordPanel.add(filler22, java.awt.BorderLayout.LINE_END);

        regJournalMainPanel.add(regJournalPasswordPanel);

        regJournalBtnPanel.setBackground(new java.awt.Color(54, 33, 89));
        regJournalBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regJournalBtnPanel.setMaximumSize(new java.awt.Dimension(100, 100));
        regJournalBtnPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        regJournalBtnPanel.setLayout(new java.awt.BorderLayout());

        regJournalBtn.setBackground(new java.awt.Color(64, 43, 100));
        regJournalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regJournalBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        regJournalBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        regJournalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regJournalBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        regJournalBtn.setLayout(new java.awt.BorderLayout());

        regJournalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regJournalLabel.setForeground(new java.awt.Color(204, 204, 204));
        regJournalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regJournalLabel.setText("Register");
        regJournalBtn.add(regJournalLabel, java.awt.BorderLayout.CENTER);

        regJournalBtnPanel.add(regJournalBtn, java.awt.BorderLayout.CENTER);
        regJournalBtnPanel.add(filler23, java.awt.BorderLayout.SOUTH);

        regJournalMainPanel.add(regJournalBtnPanel);

        regJournalPanel.add(regJournalMainPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(regJournalPanel, "regJournalPanel");

        bg.add(mainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int frmWidth = 400;
    int frmHeight = 300;
    
    private java.awt.Dimension getFrameSize(){
        return new java.awt.Dimension(frmWidth, frmHeight);
    }
    
    private java.awt.Point getStartupLocation(){
        java.awt.Toolkit kit = java.awt.Toolkit.getDefaultToolkit();
        int screenwidth=kit.getScreenSize().width;
        int screenheight=kit.getScreenSize().height;
        int frmwidth = frmWidth;
        int frmheight = frmHeight;
        java.awt.Point p = new java.awt.Point(screenwidth/2-frmwidth/2, screenheight/2-frmheight/2);
        return p;
    }
    
    private void setColor(javax.swing.JPanel panel){
        panel.setBackground(new java.awt.Color(85, 65, 118));
    }
    
    private void resetColor(javax.swing.JPanel panel){
        panel.setBackground(new java.awt.Color(64, 43, 100));
    }
    
    int dx, dy;
    
    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        dx = evt.getX();
        dy = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - dx, y - dy);
    }//GEN-LAST:event_bgMouseDragged

    private void loginUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginUserBtnMouseClicked
        java.awt.CardLayout card = (java.awt.CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "loginPanel");
    }//GEN-LAST:event_loginUserBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        java.awt.CardLayout card = (java.awt.CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "startupPanel");
    }//GEN-LAST:event_backBtnMouseClicked

    private void loginReaderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginReaderBtnMouseClicked
        // TODO : Login as Reader
    }//GEN-LAST:event_loginReaderBtnMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO : Login as User
    }//GEN-LAST:event_loginBtnMouseClicked

    private void registerReviewerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerReviewerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerReviewerBtnMouseClicked

    private void registerJournalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerJournalBtnMouseClicked
        java.awt.CardLayout card = (java.awt.CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "regJournalPanel");
    }//GEN-LAST:event_registerJournalBtnMouseClicked

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        resetColor(((javax.swing.JPanel)evt.getSource()));
    }//GEN-LAST:event_btnMouseExited

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        setColor(((javax.swing.JPanel)evt.getSource()));
    }//GEN-LAST:event_btnMouseEntered

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void regJournalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regJournalBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_regJournalBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel backLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel closeBtn;
    private javax.swing.JLabel closeLabel;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler30;
    private javax.swing.Box.Filler filler31;
    private javax.swing.Box.Filler filler32;
    private javax.swing.Box.Filler filler33;
    private javax.swing.Box.Filler filler34;
    private javax.swing.Box.Filler filler35;
    private javax.swing.Box.Filler filler36;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JPanel loginBtnPanel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginMainPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel loginReaderBtn;
    private javax.swing.JLabel loginReaderLabel;
    private javax.swing.JLabel loginReaderLabel1;
    private javax.swing.JPanel loginSelPanel;
    private javax.swing.JPanel loginToobarPanel;
    private javax.swing.JPanel loginUserBtn;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPanel regJournalBtn;
    private javax.swing.JPanel regJournalBtnPanel;
    private javax.swing.JLabel regJournalJournalNameLabel;
    private javax.swing.JPanel regJournalJournalNamePanel;
    private javax.swing.JTextField regJournalJournalNameTextField;
    private javax.swing.JLabel regJournalLabel;
    private javax.swing.JPanel regJournalMainPanel;
    private javax.swing.JPanel regJournalPanel;
    private javax.swing.JPasswordField regJournalPasswordField;
    private javax.swing.JLabel regJournalPasswordLabel;
    private javax.swing.JPanel regJournalPasswordPanel;
    private javax.swing.JPanel regJournalToobarPanel;
    private javax.swing.JLabel regJournalUsernameLabel;
    private javax.swing.JPanel regJournalUsernamePanel;
    private javax.swing.JTextField regJournalUsernameTextField;
    private javax.swing.JPanel regJournalbackBtn;
    private javax.swing.JLabel regJournalbackLabel;
    private javax.swing.JPanel registerJournalBtn;
    private javax.swing.JLabel registerJournalLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPanel registerReviewerBtn;
    private javax.swing.JLabel registerReviewerLabel;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JPanel rolePanel;
    private javax.swing.JPanel selePanel;
    private javax.swing.JPanel startupPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel welLabel;
    // End of variables declaration//GEN-END:variables
}
