/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.com2008.journalmanagementsystem;

/**
 *
 * @author Xuan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        titleLabel = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        closeBtn = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        startupPanel = new javax.swing.JPanel();
        selePanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        welLabel = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginSelPanel = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        loginReaderBtn = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        loginReaderLabel = new javax.swing.JLabel();
        loginReaderLabel1 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        loginUserBtn = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        registerPanel = new javax.swing.JPanel();
        registerReviewerBtn = new javax.swing.JPanel();
        registerReviewerLabel = new javax.swing.JLabel();
        registerJournalBtn = new javax.swing.JPanel();
        registerJournalLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        loginToobarPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        loginMainPanel = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        passwordPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        loginBtnPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        registerJournalPanel = new javax.swing.JPanel();
        loginToobarPanel1 = new javax.swing.JPanel();
        backBtn1 = new javax.swing.JPanel();
        backLabel1 = new javax.swing.JLabel();
        loginMainPanel1 = new javax.swing.JPanel();
        usernamePanel1 = new javax.swing.JPanel();
        usernameLabel1 = new javax.swing.JLabel();
        usernameTextField1 = new javax.swing.JTextField();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        passwordPanel1 = new javax.swing.JPanel();
        passwordLabel1 = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JPasswordField();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        loginBtnPanel1 = new javax.swing.JPanel();
        loginBtn1 = new javax.swing.JPanel();
        loginLabel1 = new javax.swing.JLabel();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(getStartupLocation());
        setUndecorated(true);
        setPreferredSize(getFrameSize());
        setSize(getFrameSize());

        bg.setBackground(new java.awt.Color(54, 33, 89));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(54, 33, 89));
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        headerPanel.setLayout(new javax.swing.BoxLayout(headerPanel, javax.swing.BoxLayout.LINE_AXIS));
        headerPanel.add(filler10);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 204, 204));
        titleLabel.setText("Login");
        headerPanel.add(titleLabel);
        headerPanel.add(filler12);

        closeBtn.setBackground(new java.awt.Color(64, 43, 100));
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.setMaximumSize(new java.awt.Dimension(30, 30));
        closeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        closeBtn.setLayout(new java.awt.BorderLayout());

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("×");
        closeBtn.add(closeLabel, java.awt.BorderLayout.CENTER);

        headerPanel.add(closeBtn);

        bg.add(headerPanel, java.awt.BorderLayout.NORTH);

        mainPanel.setLayout(new java.awt.CardLayout());

        startupPanel.setLayout(new java.awt.BorderLayout());

        selePanel.setBackground(new java.awt.Color(54, 33, 89));
        selePanel.setLayout(new javax.swing.BoxLayout(selePanel, javax.swing.BoxLayout.PAGE_AXIS));
        selePanel.add(filler4);

        welLabel.setBackground(new java.awt.Color(255, 255, 255));
        welLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welLabel.setForeground(new java.awt.Color(204, 204, 204));
        welLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welLabel.setText("Welcome");
        welLabel.setAlignmentX(0.5F);
        selePanel.add(welLabel);
        selePanel.add(filler5);

        loginSelPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginSelPanel.setLayout(new javax.swing.BoxLayout(loginSelPanel, javax.swing.BoxLayout.LINE_AXIS));
        loginSelPanel.add(filler8);

        loginReaderBtn.setBackground(new java.awt.Color(64, 43, 100));
        loginReaderBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginReaderBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        loginReaderBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        loginReaderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginReaderBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginReaderBtn.setLayout(new java.awt.GridLayout(4, 1));
        loginReaderBtn.add(filler11);

        loginReaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginReaderLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginReaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginReaderLabel.setText("Enter as a");
        loginReaderBtn.add(loginReaderLabel);

        loginReaderLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginReaderLabel1.setForeground(new java.awt.Color(204, 204, 204));
        loginReaderLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginReaderLabel1.setText("Reader");
        loginReaderBtn.add(loginReaderLabel1);

        loginSelPanel.add(loginReaderBtn);
        loginSelPanel.add(filler7);

        loginUserBtn.setBackground(new java.awt.Color(64, 43, 100));
        loginUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginUserBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        loginUserBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        loginUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginUserBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginUserBtn.setLayout(new java.awt.BorderLayout());

        loginUserLabel.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        loginUserLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginUserLabel.setText("Login");
        loginUserBtn.add(loginUserLabel, java.awt.BorderLayout.CENTER);

        loginSelPanel.add(loginUserBtn);
        loginSelPanel.add(filler9);

        selePanel.add(loginSelPanel);
        selePanel.add(filler6);

        startupPanel.add(selePanel, java.awt.BorderLayout.CENTER);

        registerPanel.setLayout(new java.awt.GridLayout(1, 2));

        registerReviewerBtn.setBackground(new java.awt.Color(64, 43, 100));
        registerReviewerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerReviewerBtn.setMaximumSize(new java.awt.Dimension(100, 30));
        registerReviewerBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        registerReviewerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerReviewerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        registerReviewerBtn.setLayout(new java.awt.BorderLayout());

        registerReviewerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerReviewerLabel.setForeground(new java.awt.Color(204, 204, 204));
        registerReviewerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerReviewerLabel.setText("I want to be a reviewer");
        registerReviewerBtn.add(registerReviewerLabel, java.awt.BorderLayout.CENTER);

        registerPanel.add(registerReviewerBtn);

        registerJournalBtn.setBackground(new java.awt.Color(64, 43, 100));
        registerJournalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerJournalBtn.setMaximumSize(new java.awt.Dimension(100, 30));
        registerJournalBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        registerJournalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerJournalBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        registerJournalBtn.setLayout(new java.awt.BorderLayout());

        registerJournalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerJournalLabel.setForeground(new java.awt.Color(204, 204, 204));
        registerJournalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerJournalLabel.setText("I want to register a journal");
        registerJournalBtn.add(registerJournalLabel, java.awt.BorderLayout.CENTER);

        registerPanel.add(registerJournalBtn);

        startupPanel.add(registerPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.add(startupPanel, "startupPanel");

        loginPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginPanel.setLayout(new java.awt.BorderLayout());

        loginToobarPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginToobarPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        loginToobarPanel.setLayout(new javax.swing.BoxLayout(loginToobarPanel, javax.swing.BoxLayout.LINE_AXIS));

        backBtn.setBackground(new java.awt.Color(64, 43, 100));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setMaximumSize(new java.awt.Dimension(60, 30));
        backBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        backBtn.setLayout(new java.awt.BorderLayout());

        backLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("< Back");
        backBtn.add(backLabel, java.awt.BorderLayout.CENTER);

        loginToobarPanel.add(backBtn);

        loginPanel.add(loginToobarPanel, java.awt.BorderLayout.NORTH);

        loginMainPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginMainPanel.setLayout(new java.awt.GridLayout(3, 1));

        usernamePanel.setBackground(new java.awt.Color(54, 33, 89));
        usernamePanel.setLayout(new java.awt.BorderLayout());

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel.setText("      Username: ");
        usernamePanel.add(usernameLabel, java.awt.BorderLayout.WEST);
        usernamePanel.add(usernameTextField, java.awt.BorderLayout.CENTER);
        usernamePanel.add(filler1, java.awt.BorderLayout.NORTH);
        usernamePanel.add(filler2, java.awt.BorderLayout.SOUTH);
        usernamePanel.add(filler3, java.awt.BorderLayout.LINE_END);

        loginMainPanel.add(usernamePanel);

        passwordPanel.setBackground(new java.awt.Color(54, 33, 89));
        passwordPanel.setLayout(new java.awt.BorderLayout());

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel.setText("      Password:  ");
        passwordPanel.add(passwordLabel, java.awt.BorderLayout.WEST);
        passwordPanel.add(passwordField, java.awt.BorderLayout.CENTER);
        passwordPanel.add(filler13, java.awt.BorderLayout.NORTH);
        passwordPanel.add(filler14, java.awt.BorderLayout.SOUTH);
        passwordPanel.add(filler15, java.awt.BorderLayout.LINE_END);

        loginMainPanel.add(passwordPanel);

        loginBtnPanel.setBackground(new java.awt.Color(54, 33, 89));
        loginBtnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtnPanel.setMaximumSize(new java.awt.Dimension(100, 100));
        loginBtnPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        loginBtnPanel.setLayout(new java.awt.BorderLayout());

        loginBtn.setBackground(new java.awt.Color(64, 43, 100));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        loginBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });
        loginBtn.setLayout(new java.awt.BorderLayout());

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");
        loginBtn.add(loginLabel, java.awt.BorderLayout.CENTER);

        loginBtnPanel.add(loginBtn, java.awt.BorderLayout.CENTER);
        loginBtnPanel.add(filler17, java.awt.BorderLayout.SOUTH);

        loginMainPanel.add(loginBtnPanel);

        loginPanel.add(loginMainPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(loginPanel, "loginPanel");

        registerJournalPanel.setBackground(new java.awt.Color(54, 33, 89));
        registerJournalPanel.setLayout(new java.awt.BorderLayout());

        loginToobarPanel1.setBackground(new java.awt.Color(54, 33, 89));
        loginToobarPanel1.setPreferredSize(new java.awt.Dimension(400, 30));
        loginToobarPanel1.setLayout(new javax.swing.BoxLayout(loginToobarPanel1, javax.swing.BoxLayout.LINE_AXIS));

        backBtn1.setBackground(new java.awt.Color(64, 43, 100));
        backBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn1.setMaximumSize(new java.awt.Dimension(60, 30));
        backBtn1.setPreferredSize(new java.awt.Dimension(60, 30));
        backBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtn1btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtn1btnMouseExited(evt);
            }
        });
        backBtn1.setLayout(new java.awt.BorderLayout());

        backLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backLabel1.setForeground(new java.awt.Color(255, 255, 255));
        backLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel1.setText("< Back");
        backBtn1.add(backLabel1, java.awt.BorderLayout.CENTER);

        loginToobarPanel1.add(backBtn1);

        registerJournalPanel.add(loginToobarPanel1, java.awt.BorderLayout.NORTH);

        loginMainPanel1.setBackground(new java.awt.Color(54, 33, 89));
        loginMainPanel1.setLayout(new java.awt.GridLayout(3, 1));

        usernamePanel1.setBackground(new java.awt.Color(54, 33, 89));
        usernamePanel1.setLayout(new java.awt.BorderLayout());

        usernameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(204, 204, 204));
        usernameLabel1.setText("      Username: ");
        usernamePanel1.add(usernameLabel1, java.awt.BorderLayout.WEST);
        usernamePanel1.add(usernameTextField1, java.awt.BorderLayout.CENTER);
        usernamePanel1.add(filler16, java.awt.BorderLayout.NORTH);
        usernamePanel1.add(filler18, java.awt.BorderLayout.SOUTH);
        usernamePanel1.add(filler19, java.awt.BorderLayout.LINE_END);

        loginMainPanel1.add(usernamePanel1);

        passwordPanel1.setBackground(new java.awt.Color(54, 33, 89));
        passwordPanel1.setLayout(new java.awt.BorderLayout());

        passwordLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel1.setText("      Password:  ");
        passwordPanel1.add(passwordLabel1, java.awt.BorderLayout.WEST);
        passwordPanel1.add(passwordField1, java.awt.BorderLayout.CENTER);
        passwordPanel1.add(filler20, java.awt.BorderLayout.NORTH);
        passwordPanel1.add(filler21, java.awt.BorderLayout.SOUTH);
        passwordPanel1.add(filler22, java.awt.BorderLayout.LINE_END);

        loginMainPanel1.add(passwordPanel1);

        loginBtnPanel1.setBackground(new java.awt.Color(54, 33, 89));
        loginBtnPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtnPanel1.setMaximumSize(new java.awt.Dimension(100, 100));
        loginBtnPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        loginBtnPanel1.setLayout(new java.awt.BorderLayout());

        loginBtn1.setBackground(new java.awt.Color(64, 43, 100));
        loginBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn1.setMaximumSize(new java.awt.Dimension(100, 100));
        loginBtn1.setPreferredSize(new java.awt.Dimension(100, 100));
        loginBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtn1btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtn1btnMouseExited(evt);
            }
        });
        loginBtn1.setLayout(new java.awt.BorderLayout());

        loginLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginLabel1.setForeground(new java.awt.Color(204, 204, 204));
        loginLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel1.setText("Login");
        loginBtn1.add(loginLabel1, java.awt.BorderLayout.CENTER);

        loginBtnPanel1.add(loginBtn1, java.awt.BorderLayout.CENTER);
        loginBtnPanel1.add(filler23, java.awt.BorderLayout.SOUTH);

        loginMainPanel1.add(loginBtnPanel1);

        registerJournalPanel.add(loginMainPanel1, java.awt.BorderLayout.CENTER);

        mainPanel.add(registerJournalPanel, "loginPanel");

        bg.add(mainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int frmWidth = 400;
    int frmHeight = 300;
    
    private java.awt.Dimension getFrameSize(){
        return new java.awt.Dimension(frmWidth, frmHeight);
    }
    
    private java.awt.Point getStartupLocation(){
        java.awt.Toolkit kit = java.awt.Toolkit.getDefaultToolkit();
        int screenwidth=kit.getScreenSize().width;
        int screenheight=kit.getScreenSize().height;
        int frmwidth = frmWidth;
        int frmheight = frmHeight;
        java.awt.Point p = new java.awt.Point(screenwidth/2-frmwidth/2, screenheight/2-frmheight/2);
        return p;
    }
    
    private void setColor(javax.swing.JPanel panel){
        panel.setBackground(new java.awt.Color(85, 65, 118));
    }
    
    private void resetColor(javax.swing.JPanel panel){
        panel.setBackground(new java.awt.Color(64, 43, 100));
    }
    
    int dx, dy;
    
    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        dx = evt.getX();
        dy = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - dx, y - dy);
    }//GEN-LAST:event_bgMouseDragged

    private void loginUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginUserBtnMouseClicked
        java.awt.CardLayout card = (java.awt.CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "loginPanel");
    }//GEN-LAST:event_loginUserBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        java.awt.CardLayout card = (java.awt.CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "startupPanel");
    }//GEN-LAST:event_backBtnMouseClicked

    private void loginReaderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginReaderBtnMouseClicked
        // TODO : Login as Reader
    }//GEN-LAST:event_loginReaderBtnMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO : Login as User
    }//GEN-LAST:event_loginBtnMouseClicked

    private void registerReviewerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerReviewerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerReviewerBtnMouseClicked

    private void registerJournalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerJournalBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJournalBtnMouseClicked

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        resetColor(((javax.swing.JPanel)evt.getSource()));
    }//GEN-LAST:event_btnMouseExited

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        setColor(((javax.swing.JPanel)evt.getSource()));
    }//GEN-LAST:event_btnMouseEntered

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void backBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn1MouseClicked

    private void backBtn1btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtn1btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn1btnMouseEntered

    private void backBtn1btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtn1btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn1btnMouseExited

    private void loginBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1MouseClicked

    private void loginBtn1btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1btnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1btnMouseEntered

    private void loginBtn1btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtn1btnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtn1btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backBtn;
    private javax.swing.JPanel backBtn1;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel backLabel1;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel closeBtn;
    private javax.swing.JLabel closeLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JPanel loginBtn1;
    private javax.swing.JPanel loginBtnPanel;
    private javax.swing.JPanel loginBtnPanel1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JPanel loginMainPanel;
    private javax.swing.JPanel loginMainPanel1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel loginReaderBtn;
    private javax.swing.JLabel loginReaderLabel;
    private javax.swing.JLabel loginReaderLabel1;
    private javax.swing.JPanel loginSelPanel;
    private javax.swing.JPanel loginToobarPanel;
    private javax.swing.JPanel loginToobarPanel1;
    private javax.swing.JPanel loginUserBtn;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPanel passwordPanel1;
    private javax.swing.JPanel registerJournalBtn;
    private javax.swing.JLabel registerJournalLabel;
    private javax.swing.JPanel registerJournalPanel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPanel registerReviewerBtn;
    private javax.swing.JLabel registerReviewerLabel;
    private javax.swing.JPanel selePanel;
    private javax.swing.JPanel startupPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JPanel usernamePanel;
    private javax.swing.JPanel usernamePanel1;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JTextField usernameTextField1;
    private javax.swing.JLabel welLabel;
    // End of variables declaration//GEN-END:variables
}
